import pytest

from flext_ldif import FlextLdifAPI

class TestAPIIntegration:
    @pytest.fixture
    def api(self) -> FlextLdifAPI: ...
    @pytest.fixture
    def sample_ldif_content(self) -> str: ...
    def test_parse_and_validate_flow(
        self, api: FlextLdifAPI, sample_ldif_content: str
    ) -> None: ...
    def test_parse_and_write_flow(
        self, api: FlextLdifAPI, sample_ldif_content: str
    ) -> None: ...
    def test_file_operations(
        self, api: FlextLdifAPI, sample_ldif_content: str
    ) -> None: ...
    def test_api_with_custom_config(self, sample_ldif_content: str) -> None: ...
    def test_error_handling(self, api: FlextLdifAPI) -> None: ...
