# from flext-ldif_docs/guides/flext_ldif_parse_acl_usages.md:188
from __future__ import annotations


def test_parse_oracle_oid():
    """Test OID ACL parsing."""
    server = FlextLdifServersOid.Acl()
    acl_line = "orclaci: access to entry by * (browse)"

    result = server.parse(acl_line)

    assert result.success
    acl = result.unwrap()
    assert isinstance(acl, FlextLdifModels.Acl)  # ← Tests Acl return type
    assert acl.server_type == "oid"```
**Total Tests**: ~50+ test methods using parse()

______________________________________________________________________

## 5. INTEGRATION POINTS

### FlextLdifCategorizedMigrationPipeline

**File**: `~/flext/flext-ldif/src/flext_ldif/categorized_pipeline.py`

**Usage Context**:

- Initializes OID and OUD servers
- Calls `_transform_categories()` which uses parse()
- Returns transformed entries with OUD format ACLs

**Impact**: HIGH - Core migration pipeline uses parse()

### ldif High-Level API

**File**: `~/flext/flext-ldif/src/flext_ldif/__init__.py`

**Exposure**:

- `ldif.parse()` uses servers internally but doesn't expose parse()
- Higher-level API returns Entry models (not Acl models)
- algar-oud-mig uses this API (already compatible with Entry return)

______________________________________________________________________

## 6. CURRENT DATA FLOW```
Input LDIF with OID ACL (orclaci:)
    ↓
ldif.parse() → FlextLdifModels.Entry[]
    ↓ (internal servers usage)
parse(acl_line: str) → r[FlextLdifModels.Acl]
    ↓
Entry model with aci attributes (after transformation)
    ↓
Output LDIF with OUD format (aci:)```
______________________________________________________________________

## 7. AFFECTED CODE LOCATIONS (SUMMARY)

### Must Be Updated (High Impact)

1. **Protocol Definition** (3-5 lines)

   - `/flext_ldif/protocols.py` - Update Acl signature

1. **Base Class** (10-15 lines)

   - `/flext_ldif/servers/base.py` - Update FlextLdifServersBase.Acl.parse()

1. **13 Server Servers** (520-650 lines)

   - All 13 servers files in `/flext_ldif/servers/servers/`
   - Each file needs parse() method signature updated

1. **Service Layer** (30-50 lines)

   - `/flext_ldif/services/acl.py` - Update parse() wrapper
   - `/flext_ldif/categorized_pipeline.py` - Update transformation logic

1. **Tests** (1000+ lines)

   - 50+ test methods in 4+ test files
   - Mock returns, assertions, fixture data

### Should Review (Medium Impact)

1. **Integration Tests** (tests/integration/)

   - May have parse() calls in fixtures or helpers

1. **Examples** (examples/06_acl_processing.py)

   - Documentation examples using parse()

1. **Type Hints**

   - Any type hints expecting Acl model need updating

______________________________________________________________________

## 8. MIGRATION STRATEGY

### Phase 1: Update Interfaces (2-3 hours)

- [ ] Update protocol definition in protocols.py
- [ ] Update base class in servers/base.py
- [ ] Update service wrapper in services/acl.py

### Phase 2: Update Implementations (4-6 hours)

- [ ] Update all 13 server servers
- [ ] Create Entry wrapper logic if needed
- [ ] Update categorized_pipeline.py

### Phase 3: Update Tests (2-3 hours)

- [ ] Update test files to expect Entry return
- [ ] Update assertions and mocks
- [ ] Add Entry wrapping tests

### Phase 4: Validation (2-3 hours)

- [ ] Run full test suite
- [ ] Test with real LDIF data
- [ ] Verify algar-oud-mig compatibility (should be automatic)

**Total Estimated Time**: 10-15 hours of development

______________________________________________________________________

## 9. ECOSYSTEM IMPACT

### Projects Using flext-ldif

**Dependent on parse()/format_acl()**:

1. algar-oud-mig - Uses via ldif.parse() (COMPATIBLE)
1. Any other projects importing from flext-ldif

**Risk Assessment**:

- algar-oud-mig: 🟢 **NO CHANGES NEEDED** (uses high-level API)
- flext-ldif itself: 🔴 **EXTENSIVE CHANGES REQUIRED**
- Other ecosytem projects: 🟡 **REVIEW REQUIRED** (depends on usage)

______________________________________________________________________

## CONCLUSION

The parse() and format_acl() return type change requires **significant refactoring** within flext-ldif but does **NOT impact algar-oud-mig** because:

1. algar-oud-mig uses `ldif.parse()` (high-level API) which returns Entry models
1. algar-oud-mig does not directly call parse() or format_acl()
1. The change is internal to flext-ldif's servers system

**Recommendation**: Implement the change in flext-ldif, test thoroughly, then verify algar-oud-mig continues to work (should be automatic with no code changes).

______________________________________________________________________

**Generated By**: Claude Code
**Tools Used**: Grep, Read, Bash
**Scope**: Complete flext-ldif ACL method analysis
