from flext_core import FlextDomainService, FlextResult

from flext_ldif.config import FlextLdifConfig
from flext_ldif.models import FlextLdifEntry

__all__ = ["FlextLdifValidatorService"]

class FlextLdifValidatorService(FlextDomainService[bool]):
    config: FlextLdifConfig | None
    def execute(self) -> FlextResult[bool]: ...
    def validate_data(self, data: list[FlextLdifEntry]) -> FlextResult[bool]: ...
    def validate_entry(self, entry: FlextLdifEntry) -> FlextResult[bool]: ...
    def validate_entries(self, entries: list[FlextLdifEntry]) -> FlextResult[bool]: ...
    def validate_dn_format(self, dn: str) -> FlextResult[bool]: ...
