class TestFlextLdifConfig:
    def test_config_initialization_default(self) -> None: ...
    def test_config_initialization_with_params(self) -> None: ...
    def test_config_validation(self) -> None: ...
    def test_config_properties(self) -> None: ...
