class TestConstants:
    def test_ldap_person_classes_defined(self) -> None: ...
    def test_ldap_group_classes_defined(self) -> None: ...
    def test_ldap_dn_attributes_defined(self) -> None: ...
    def test_min_dn_components_defined(self) -> None: ...
