class TestFlextLdifExceptions:
    def test_flext_ldif_error_default(self) -> None: ...
    def test_flext_ldif_error_custom_message(self) -> None: ...
    def test_flext_ldif_parse_error_inheritance(self) -> None: ...
    def test_flext_ldif_validation_error_inheritance(self) -> None: ...
    def test_flext_ldif_entry_error_inheritance(self) -> None: ...
    def test_exception_hierarchy(self) -> None: ...
    def test_exception_can_be_raised_and_caught(self) -> None: ...
    def test_exception_messages(self) -> None: ...
