class TestFlextLdifValidSpecification:
    def test_valid_entry_with_objectclass(self) -> None: ...
    def test_invalid_entry_no_objectclass(self) -> None: ...
    def test_invalid_entry_malformed_dn(self) -> None: ...
    def test_invalid_entry_empty_dn(self) -> None: ...

class TestFlextLdifPersonSpecification:
    def test_person_entry(self) -> None: ...
    def test_organizational_person_entry(self) -> None: ...
    def test_inet_org_person_entry(self) -> None: ...
    def test_user_entry(self) -> None: ...
    def test_posix_account_entry(self) -> None: ...
    def test_non_person_entry(self) -> None: ...
    def test_entry_no_objectclass(self) -> None: ...
