from flext_ldif import FlextLdifEntry

LDIFEntry = FlextLdifEntry

class TestLDIFEntry:
    def test_ldif_entry_creation(self) -> None: ...
    def test_ldif_entry_default_attributes(self) -> None: ...
    def test_get_attribute_exists(self) -> None: ...
    def test_get_attribute_not_exists(self) -> None: ...
    def test_set_attribute(self) -> None: ...
    def test_set_attribute_overwrites(self) -> None: ...
    def test_has_attribute_true(self) -> None: ...
    def test_has_attribute_false(self) -> None: ...
    def test_get_single_attribute_exists(self) -> None: ...
    def test_get_single_attribute_not_exists(self) -> None: ...
    def test_get_single_attribute_empty_list(self) -> None: ...
    def test_to_ldif(self) -> None: ...
    def test_from_ldif_block_valid(self) -> None: ...
    def test_from_ldif_block_empty(self) -> None: ...
    def test_from_ldif_block_whitespace_only(self) -> None: ...
    def test_from_ldif_block_no_dn(self) -> None: ...
    def test_from_ldif_block_dn_only(self) -> None: ...
    def test_from_ldif_block_with_whitespace(self) -> None: ...
    def test_from_ldif_block_multiple_values(self) -> None: ...
    def test_from_ldif_block_colon_in_value(self) -> None: ...
    def test_from_ldif_block_invalid_line_no_colon(self) -> None: ...
