class TestModuleImports:
    def test_main_imports(self) -> None: ...
    def test_service_imports(self) -> None: ...
    def test_legacy_function_imports(self) -> None: ...
    def test_cli_import(self) -> None: ...
    def test_version_import(self) -> None: ...
    def test_individual_module_imports(self) -> None: ...
    def test_service_module_imports(self) -> None: ...
    def test_format_module_imports(self) -> None: ...
