# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make codegen
#
"""Tests package."""

from __future__ import annotations

from typing import TYPE_CHECKING

from flext_core.lazy import cleanup_submodule_namespace, lazy_getattr

if TYPE_CHECKING:
    from flext_core.typings import FlextTypes

    from flext_ldif import d, e, h, r, s, t, x

    from . import integration as integration, support as support, unit as unit
    from .base import FlextLdifTestsServiceBase
    from .conftest import (
        FIXTURES_DIR,
        OID_FIXTURES_DIR,
        FlextLdifFixtures,
        flext_ldif,
        ldif_parser,
        ldif_writer,
        pytest_configure,
        real_ldif_group_entry,
        real_ldif_multiple_entries,
        real_ldif_user_entry,
        sample_ldif_entries,
        temp_file,
    )
    from .conftest_shared import (
        large_test_dataset,
        parametrized_real_data,
        real_entry,
        real_ldif_content,
    )
    from .constants import TestsFlextLdifConstants, TestsFlextLdifConstants as c
    from .integration import (
        APIScenarios,
        ConfigTestData,
        TestAclRoundTripPreservation,
        TestBoundaryValues,
        TestCategorizationRealData,
        TestData,
        TestDnCaseNormalizationScenarios,
        TestDnCaseRegistry,
        TestEmptyAndMinimalCases,
        TestEncodingErrors,
        TestFlextLdifAPIIntegration,
        TestFlextLdifFacadeWorkflows,
        TestFlextLdifSettingsIntegration,
        TestIncompleteEntries,
        TestInvalidSchemaDefinitions,
        TestLargeAndComplexCases,
        TestMalformedLdifHandling,
        TestMinimalDifferencesOidOud,
        TestOidAclMetadataPreservation,
        TestOidEntryIntegration,
        TestOidQuirksTransformations,
        TestOidRoundTripIntegration,
        TestOidSchemaIntegration,
        TestOidToOudAclConversion,
        TestOidToOudIntegrationConversion,
        TestOidToOudSchemaConversion,
        TestOudAciMetadataPreservation,
        TestOudAclIntegration,
        TestOudEntryIntegration,
        TestOudMetadataPreservation,
        TestOudQuirksTransformations,
        TestOudRoundTripIntegration,
        TestOudSchemaIntegration,
        TestOudToOidAclMigration,
        TestOudToOidEntryMigration,
        TestOudToOidFullMigration,
        TestOudToOidSchemaMigration,
        TestQuirksConversionMatrixFacade,
        TestQuirksPropertyValidation,
        TestRealLdapBatchOperations,
        TestRealLdapConfigurationFromEnv,
        TestRealLdapCRUD,
        TestRealLdapExport,
        TestRealLdapImport,
        TestRealLdapRailwayComposition,
        TestRealLdapRoundtrip,
        TestRfcDockerRealData,
        TestRfcExceptionHandlingRealScenarios,
        TestRfcIntegrationRealWorld,
        TestRfcParserRealFixtures,
        TestRfcSchemaParserRealFixtures,
        TestRfcWriterRealFixtures,
        TestRoundtripEdgeCases,
        TestSchemaDeviationsAttributeKeyCasing,
        TestSchemaDeviationsComplete,
        TestSchemaDeviationsMissingSpaces,
        TestSchemaDeviationsNameAliases,
        TestSchemaDeviationsObsolete,
        TestSchemaDeviationsOriginalString,
        TestSchemaDeviationsRoundTrip,
        TestSchemaDeviationsSpacing,
        TestSchemaDeviationsSyntaxQuotes,
        TestSchemaDeviationsUtilities,
        TestSchemaDeviationsXOrigin,
        TestSystematicFixtureCoverage,
        TestUnicodeBoundaries,
        TestZeroDataLossOidOud,
        all_acl_fixtures,
        all_entries_fixtures,
        all_integration_fixtures,
        all_schema_fixtures,
        api,
        clean_test_ou,
        conversion_matrix,
        fixtures_dir,
        ldap_connection,
        ldap_container,
        ldap_container_shared,
        logger,
        make_test_base_dn,
        make_test_username,
        migration_inputs,
        oid_acl_fixture,
        oid_acl_quirk,
        oid_entries,
        oid_entries_fixture,
        oid_integration_fixture,
        oid_quirk,
        oid_schema_entries,
        oid_schema_fixture,
        oid_schema_quirk,
        openldap_acl_fixture,
        openldap_entries,
        openldap_entries_fixture,
        openldap_integration_fixture,
        openldap_schema_entries,
        openldap_schema_fixture,
        oud_acl_fixture,
        oud_acl_quirk,
        oud_entries,
        oud_entries_fixture,
        oud_integration_fixture,
        oud_quirk,
        oud_schema_entries,
        oud_schema_fixture,
        oud_schema_quirk,
        parser,
        rfc_schema_entries,
        rfc_schema_fixture,
        server,
        test_create_and_export_entry,
        test_ldap_connection,
        test_simple_ldap_search,
        tmp_ldif_path,
        unique_dn_suffix,
        writer,
    )
    from .models import TestsFlextLdifModels, TestsFlextLdifModels as m
    from .protocols import TestsFlextLdifProtocols, TestsFlextLdifProtocols as p
    from .support import (
        FileManager,
        FlextLdifTestConftest,
        LdifSample,
        LdifTestData,
        MockFlextUtilitiesResultHelpers,
        MockMatchers,
        TestValidators,
        tk,
    )
    from .test_factory import FlextLdifTestFactory
    from .test_helpers import (
        TestsFlextLdifFixtures,
        TestsFlextLdifMatchers,
        TestsFlextLdifTypes,
        TestsFlextLdifValidators,
        tf,
        tm,
        tt,
        tv,
    )
    from .typings import GenericFieldsDict
    from .unit import (
        GetAclAttributesServerType,
        GetValidValuesType,
        IsAclAttributeType,
        IsValidTestType,
        OidTestConstants,
        TestAclAttributes,
        TestAclParser,
        TestAliasDiscovery,
        TestAttributeFixer,
        TestDnObjectClassMethods,
        TestFlextLdifDeduplicationHelpers,
        TestFlextLdifModels,
        TestFlextLdifTypesStructure,
        TestFlextLdifUtilitiesComprehensive,
        TestIntegrationWithLdifFixtures,
        TestLdifParser,
        TestModelsNamespace,
        TestObjectClassUtilities,
        TestPhase1StandardizationResults,
        TestQuirksAutoInterchange,
        TestQuirksWithRealLdifFixtures,
        TestRemovalOfOverEngineering,
        TestSchemaServiceBuilder,
        TestSchemaServiceCanHandleAttribute,
        TestSchemaServiceIntegration,
        TestSchemaServiceParseAttribute,
        TestSchemaServiceParseObjectClass,
        TestSchemaServiceRepr,
        TestSchemaServiceValidateAttribute,
        TestSchemaServiceValidateObjectClass,
        TestSchemaServiceWriteAttribute,
        TestSchemaServiceWriteObjectClass,
        TestServerTypes,
        TestsFlextLdifCommonDictionaryTypes,
        TestsFlextLdifDnOperationsPure,
        TestsFlextLdifMigrationPipeline,
        TestsFlextLdifMigrationPipelineQuirks,
        TestsFlextLdifQuirksStandardizedConstants,
        TestsFlextLdifSchemaServiceExecute,
        TestsFlextLdifsFlextLdifWriterDnNormalization,
        TestsFlextLdifVersion,
        TestsTestFlextLdifAclAttributeRegistry,
        TestsTestFlextLdifConstants,
        TestsTestFlextLdifMigrationPipeline,
        TestsTestFlextLdifProtocols,
        TestsTestFlextLdifServiceAPIs,
        ValidateManyType,
        complex_attribute_definition,
        complex_objectclass_definition,
        constants,
        models,
        protocols,
        schema_service,
        schema_service_oud,
        services,
        simple_attribute_definition,
        simple_objectclass_definition,
        utilities,
        version_module,
    )
    from .utilities import TestsFlextLdifUtilities, TestsFlextLdifUtilities as u

_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    "APIScenarios": ("tests.integration", "APIScenarios"),
    "ConfigTestData": ("tests.integration", "ConfigTestData"),
    "FIXTURES_DIR": ("tests.conftest", "FIXTURES_DIR"),
    "FileManager": ("tests.support", "FileManager"),
    "FlextLdifFixtures": ("tests.conftest", "FlextLdifFixtures"),
    "FlextLdifTestConftest": ("tests.support", "FlextLdifTestConftest"),
    "FlextLdifTestFactory": ("tests.test_factory", "FlextLdifTestFactory"),
    "FlextLdifTestsServiceBase": ("tests.base", "FlextLdifTestsServiceBase"),
    "GenericFieldsDict": ("tests.typings", "GenericFieldsDict"),
    "GetAclAttributesServerType": ("tests.unit", "GetAclAttributesServerType"),
    "GetValidValuesType": ("tests.unit", "GetValidValuesType"),
    "IsAclAttributeType": ("tests.unit", "IsAclAttributeType"),
    "IsValidTestType": ("tests.unit", "IsValidTestType"),
    "LdifSample": ("tests.support", "LdifSample"),
    "LdifTestData": ("tests.support", "LdifTestData"),
    "MockFlextUtilitiesResultHelpers": (
        "tests.support",
        "MockFlextUtilitiesResultHelpers",
    ),
    "MockMatchers": ("tests.support", "MockMatchers"),
    "OID_FIXTURES_DIR": ("tests.conftest", "OID_FIXTURES_DIR"),
    "OidTestConstants": ("tests.unit", "OidTestConstants"),
    "TestAclAttributes": ("tests.unit", "TestAclAttributes"),
    "TestAclParser": ("tests.unit", "TestAclParser"),
    "TestAclRoundTripPreservation": (
        "tests.integration",
        "TestAclRoundTripPreservation",
    ),
    "TestAliasDiscovery": ("tests.unit", "TestAliasDiscovery"),
    "TestAttributeFixer": ("tests.unit", "TestAttributeFixer"),
    "TestBoundaryValues": ("tests.integration", "TestBoundaryValues"),
    "TestCategorizationRealData": ("tests.integration", "TestCategorizationRealData"),
    "TestData": ("tests.integration", "TestData"),
    "TestDnCaseNormalizationScenarios": (
        "tests.integration",
        "TestDnCaseNormalizationScenarios",
    ),
    "TestDnCaseRegistry": ("tests.integration", "TestDnCaseRegistry"),
    "TestDnObjectClassMethods": ("tests.unit", "TestDnObjectClassMethods"),
    "TestEmptyAndMinimalCases": ("tests.integration", "TestEmptyAndMinimalCases"),
    "TestEncodingErrors": ("tests.integration", "TestEncodingErrors"),
    "TestFlextLdifAPIIntegration": ("tests.integration", "TestFlextLdifAPIIntegration"),
    "TestFlextLdifDeduplicationHelpers": (
        "tests.unit",
        "TestFlextLdifDeduplicationHelpers",
    ),
    "TestFlextLdifFacadeWorkflows": (
        "tests.integration",
        "TestFlextLdifFacadeWorkflows",
    ),
    "TestFlextLdifModels": ("tests.unit", "TestFlextLdifModels"),
    "TestFlextLdifSettingsIntegration": (
        "tests.integration",
        "TestFlextLdifSettingsIntegration",
    ),
    "TestFlextLdifTypesStructure": ("tests.unit", "TestFlextLdifTypesStructure"),
    "TestFlextLdifUtilitiesComprehensive": (
        "tests.unit",
        "TestFlextLdifUtilitiesComprehensive",
    ),
    "TestIncompleteEntries": ("tests.integration", "TestIncompleteEntries"),
    "TestIntegrationWithLdifFixtures": (
        "tests.unit",
        "TestIntegrationWithLdifFixtures",
    ),
    "TestInvalidSchemaDefinitions": (
        "tests.integration",
        "TestInvalidSchemaDefinitions",
    ),
    "TestLargeAndComplexCases": ("tests.integration", "TestLargeAndComplexCases"),
    "TestLdifParser": ("tests.unit", "TestLdifParser"),
    "TestMalformedLdifHandling": ("tests.integration", "TestMalformedLdifHandling"),
    "TestMinimalDifferencesOidOud": (
        "tests.integration",
        "TestMinimalDifferencesOidOud",
    ),
    "TestModelsNamespace": ("tests.unit", "TestModelsNamespace"),
    "TestObjectClassUtilities": ("tests.unit", "TestObjectClassUtilities"),
    "TestOidAclMetadataPreservation": (
        "tests.integration",
        "TestOidAclMetadataPreservation",
    ),
    "TestOidEntryIntegration": ("tests.integration", "TestOidEntryIntegration"),
    "TestOidQuirksTransformations": (
        "tests.integration",
        "TestOidQuirksTransformations",
    ),
    "TestOidRoundTripIntegration": ("tests.integration", "TestOidRoundTripIntegration"),
    "TestOidSchemaIntegration": ("tests.integration", "TestOidSchemaIntegration"),
    "TestOidToOudAclConversion": ("tests.integration", "TestOidToOudAclConversion"),
    "TestOidToOudIntegrationConversion": (
        "tests.integration",
        "TestOidToOudIntegrationConversion",
    ),
    "TestOidToOudSchemaConversion": (
        "tests.integration",
        "TestOidToOudSchemaConversion",
    ),
    "TestOudAciMetadataPreservation": (
        "tests.integration",
        "TestOudAciMetadataPreservation",
    ),
    "TestOudAclIntegration": ("tests.integration", "TestOudAclIntegration"),
    "TestOudEntryIntegration": ("tests.integration", "TestOudEntryIntegration"),
    "TestOudMetadataPreservation": ("tests.integration", "TestOudMetadataPreservation"),
    "TestOudQuirksTransformations": (
        "tests.integration",
        "TestOudQuirksTransformations",
    ),
    "TestOudRoundTripIntegration": ("tests.integration", "TestOudRoundTripIntegration"),
    "TestOudSchemaIntegration": ("tests.integration", "TestOudSchemaIntegration"),
    "TestOudToOidAclMigration": ("tests.integration", "TestOudToOidAclMigration"),
    "TestOudToOidEntryMigration": ("tests.integration", "TestOudToOidEntryMigration"),
    "TestOudToOidFullMigration": ("tests.integration", "TestOudToOidFullMigration"),
    "TestOudToOidSchemaMigration": ("tests.integration", "TestOudToOidSchemaMigration"),
    "TestPhase1StandardizationResults": (
        "tests.unit",
        "TestPhase1StandardizationResults",
    ),
    "TestQuirksAutoInterchange": ("tests.unit", "TestQuirksAutoInterchange"),
    "TestQuirksConversionMatrixFacade": (
        "tests.integration",
        "TestQuirksConversionMatrixFacade",
    ),
    "TestQuirksPropertyValidation": (
        "tests.integration",
        "TestQuirksPropertyValidation",
    ),
    "TestQuirksWithRealLdifFixtures": ("tests.unit", "TestQuirksWithRealLdifFixtures"),
    "TestRealLdapBatchOperations": ("tests.integration", "TestRealLdapBatchOperations"),
    "TestRealLdapCRUD": ("tests.integration", "TestRealLdapCRUD"),
    "TestRealLdapConfigurationFromEnv": (
        "tests.integration",
        "TestRealLdapConfigurationFromEnv",
    ),
    "TestRealLdapExport": ("tests.integration", "TestRealLdapExport"),
    "TestRealLdapImport": ("tests.integration", "TestRealLdapImport"),
    "TestRealLdapRailwayComposition": (
        "tests.integration",
        "TestRealLdapRailwayComposition",
    ),
    "TestRealLdapRoundtrip": ("tests.integration", "TestRealLdapRoundtrip"),
    "TestRemovalOfOverEngineering": ("tests.unit", "TestRemovalOfOverEngineering"),
    "TestRfcDockerRealData": ("tests.integration", "TestRfcDockerRealData"),
    "TestRfcExceptionHandlingRealScenarios": (
        "tests.integration",
        "TestRfcExceptionHandlingRealScenarios",
    ),
    "TestRfcIntegrationRealWorld": ("tests.integration", "TestRfcIntegrationRealWorld"),
    "TestRfcParserRealFixtures": ("tests.integration", "TestRfcParserRealFixtures"),
    "TestRfcSchemaParserRealFixtures": (
        "tests.integration",
        "TestRfcSchemaParserRealFixtures",
    ),
    "TestRfcWriterRealFixtures": ("tests.integration", "TestRfcWriterRealFixtures"),
    "TestRoundtripEdgeCases": ("tests.integration", "TestRoundtripEdgeCases"),
    "TestSchemaDeviationsAttributeKeyCasing": (
        "tests.integration",
        "TestSchemaDeviationsAttributeKeyCasing",
    ),
    "TestSchemaDeviationsComplete": (
        "tests.integration",
        "TestSchemaDeviationsComplete",
    ),
    "TestSchemaDeviationsMissingSpaces": (
        "tests.integration",
        "TestSchemaDeviationsMissingSpaces",
    ),
    "TestSchemaDeviationsNameAliases": (
        "tests.integration",
        "TestSchemaDeviationsNameAliases",
    ),
    "TestSchemaDeviationsObsolete": (
        "tests.integration",
        "TestSchemaDeviationsObsolete",
    ),
    "TestSchemaDeviationsOriginalString": (
        "tests.integration",
        "TestSchemaDeviationsOriginalString",
    ),
    "TestSchemaDeviationsRoundTrip": (
        "tests.integration",
        "TestSchemaDeviationsRoundTrip",
    ),
    "TestSchemaDeviationsSpacing": ("tests.integration", "TestSchemaDeviationsSpacing"),
    "TestSchemaDeviationsSyntaxQuotes": (
        "tests.integration",
        "TestSchemaDeviationsSyntaxQuotes",
    ),
    "TestSchemaDeviationsUtilities": (
        "tests.integration",
        "TestSchemaDeviationsUtilities",
    ),
    "TestSchemaDeviationsXOrigin": ("tests.integration", "TestSchemaDeviationsXOrigin"),
    "TestSchemaServiceBuilder": ("tests.unit", "TestSchemaServiceBuilder"),
    "TestSchemaServiceCanHandleAttribute": (
        "tests.unit",
        "TestSchemaServiceCanHandleAttribute",
    ),
    "TestSchemaServiceIntegration": ("tests.unit", "TestSchemaServiceIntegration"),
    "TestSchemaServiceParseAttribute": (
        "tests.unit",
        "TestSchemaServiceParseAttribute",
    ),
    "TestSchemaServiceParseObjectClass": (
        "tests.unit",
        "TestSchemaServiceParseObjectClass",
    ),
    "TestSchemaServiceRepr": ("tests.unit", "TestSchemaServiceRepr"),
    "TestSchemaServiceValidateAttribute": (
        "tests.unit",
        "TestSchemaServiceValidateAttribute",
    ),
    "TestSchemaServiceValidateObjectClass": (
        "tests.unit",
        "TestSchemaServiceValidateObjectClass",
    ),
    "TestSchemaServiceWriteAttribute": (
        "tests.unit",
        "TestSchemaServiceWriteAttribute",
    ),
    "TestSchemaServiceWriteObjectClass": (
        "tests.unit",
        "TestSchemaServiceWriteObjectClass",
    ),
    "TestServerTypes": ("tests.unit", "TestServerTypes"),
    "TestSystematicFixtureCoverage": (
        "tests.integration",
        "TestSystematicFixtureCoverage",
    ),
    "TestUnicodeBoundaries": ("tests.integration", "TestUnicodeBoundaries"),
    "TestValidators": ("tests.support", "TestValidators"),
    "TestZeroDataLossOidOud": ("tests.integration", "TestZeroDataLossOidOud"),
    "TestsFlextLdifCommonDictionaryTypes": (
        "tests.unit",
        "TestsFlextLdifCommonDictionaryTypes",
    ),
    "TestsFlextLdifConstants": ("tests.constants", "TestsFlextLdifConstants"),
    "TestsFlextLdifDnOperationsPure": ("tests.unit", "TestsFlextLdifDnOperationsPure"),
    "TestsFlextLdifFixtures": ("tests.test_helpers", "TestsFlextLdifFixtures"),
    "TestsFlextLdifMatchers": ("tests.test_helpers", "TestsFlextLdifMatchers"),
    "TestsFlextLdifMigrationPipeline": (
        "tests.unit",
        "TestsFlextLdifMigrationPipeline",
    ),
    "TestsFlextLdifMigrationPipelineQuirks": (
        "tests.unit",
        "TestsFlextLdifMigrationPipelineQuirks",
    ),
    "TestsFlextLdifModels": ("tests.models", "TestsFlextLdifModels"),
    "TestsFlextLdifProtocols": ("tests.protocols", "TestsFlextLdifProtocols"),
    "TestsFlextLdifQuirksStandardizedConstants": (
        "tests.unit",
        "TestsFlextLdifQuirksStandardizedConstants",
    ),
    "TestsFlextLdifSchemaServiceExecute": (
        "tests.unit",
        "TestsFlextLdifSchemaServiceExecute",
    ),
    "TestsFlextLdifTypes": ("tests.test_helpers", "TestsFlextLdifTypes"),
    "TestsFlextLdifUtilities": ("tests.utilities", "TestsFlextLdifUtilities"),
    "TestsFlextLdifValidators": ("tests.test_helpers", "TestsFlextLdifValidators"),
    "TestsFlextLdifVersion": ("tests.unit", "TestsFlextLdifVersion"),
    "TestsFlextLdifsFlextLdifWriterDnNormalization": (
        "tests.unit",
        "TestsFlextLdifsFlextLdifWriterDnNormalization",
    ),
    "TestsTestFlextLdifAclAttributeRegistry": (
        "tests.unit",
        "TestsTestFlextLdifAclAttributeRegistry",
    ),
    "TestsTestFlextLdifConstants": ("tests.unit", "TestsTestFlextLdifConstants"),
    "TestsTestFlextLdifMigrationPipeline": (
        "tests.unit",
        "TestsTestFlextLdifMigrationPipeline",
    ),
    "TestsTestFlextLdifProtocols": ("tests.unit", "TestsTestFlextLdifProtocols"),
    "TestsTestFlextLdifServiceAPIs": ("tests.unit", "TestsTestFlextLdifServiceAPIs"),
    "ValidateManyType": ("tests.unit", "ValidateManyType"),
    "all_acl_fixtures": ("tests.integration", "all_acl_fixtures"),
    "all_entries_fixtures": ("tests.integration", "all_entries_fixtures"),
    "all_integration_fixtures": ("tests.integration", "all_integration_fixtures"),
    "all_schema_fixtures": ("tests.integration", "all_schema_fixtures"),
    "api": ("tests.integration", "api"),
    "c": ("tests.constants", "TestsFlextLdifConstants"),
    "clean_test_ou": ("tests.integration", "clean_test_ou"),
    "complex_attribute_definition": ("tests.unit", "complex_attribute_definition"),
    "complex_objectclass_definition": ("tests.unit", "complex_objectclass_definition"),
    "constants": ("tests.unit", "constants"),
    "conversion_matrix": ("tests.integration", "conversion_matrix"),
    "d": ("flext_ldif", "d"),
    "e": ("flext_ldif", "e"),
    "fixtures_dir": ("tests.integration", "fixtures_dir"),
    "flext_ldif": ("tests.conftest", "flext_ldif"),
    "h": ("flext_ldif", "h"),
    "integration": ("tests.integration", ""),
    "large_test_dataset": ("tests.conftest_shared", "large_test_dataset"),
    "ldap_connection": ("tests.integration", "ldap_connection"),
    "ldap_container": ("tests.integration", "ldap_container"),
    "ldap_container_shared": ("tests.integration", "ldap_container_shared"),
    "ldif_parser": ("tests.conftest", "ldif_parser"),
    "ldif_writer": ("tests.conftest", "ldif_writer"),
    "logger": ("tests.integration", "logger"),
    "m": ("tests.models", "TestsFlextLdifModels"),
    "make_test_base_dn": ("tests.integration", "make_test_base_dn"),
    "make_test_username": ("tests.integration", "make_test_username"),
    "migration_inputs": ("tests.integration", "migration_inputs"),
    "models": ("tests.unit", "models"),
    "oid_acl_fixture": ("tests.integration", "oid_acl_fixture"),
    "oid_acl_quirk": ("tests.integration", "oid_acl_quirk"),
    "oid_entries": ("tests.integration", "oid_entries"),
    "oid_entries_fixture": ("tests.integration", "oid_entries_fixture"),
    "oid_integration_fixture": ("tests.integration", "oid_integration_fixture"),
    "oid_quirk": ("tests.integration", "oid_quirk"),
    "oid_schema_entries": ("tests.integration", "oid_schema_entries"),
    "oid_schema_fixture": ("tests.integration", "oid_schema_fixture"),
    "oid_schema_quirk": ("tests.integration", "oid_schema_quirk"),
    "openldap_acl_fixture": ("tests.integration", "openldap_acl_fixture"),
    "openldap_entries": ("tests.integration", "openldap_entries"),
    "openldap_entries_fixture": ("tests.integration", "openldap_entries_fixture"),
    "openldap_integration_fixture": (
        "tests.integration",
        "openldap_integration_fixture",
    ),
    "openldap_schema_entries": ("tests.integration", "openldap_schema_entries"),
    "openldap_schema_fixture": ("tests.integration", "openldap_schema_fixture"),
    "oud_acl_fixture": ("tests.integration", "oud_acl_fixture"),
    "oud_acl_quirk": ("tests.integration", "oud_acl_quirk"),
    "oud_entries": ("tests.integration", "oud_entries"),
    "oud_entries_fixture": ("tests.integration", "oud_entries_fixture"),
    "oud_integration_fixture": ("tests.integration", "oud_integration_fixture"),
    "oud_quirk": ("tests.integration", "oud_quirk"),
    "oud_schema_entries": ("tests.integration", "oud_schema_entries"),
    "oud_schema_fixture": ("tests.integration", "oud_schema_fixture"),
    "oud_schema_quirk": ("tests.integration", "oud_schema_quirk"),
    "p": ("tests.protocols", "TestsFlextLdifProtocols"),
    "parametrized_real_data": ("tests.conftest_shared", "parametrized_real_data"),
    "parser": ("tests.integration", "parser"),
    "protocols": ("tests.unit", "protocols"),
    "pytest_configure": ("tests.conftest", "pytest_configure"),
    "r": ("flext_ldif", "r"),
    "real_entry": ("tests.conftest_shared", "real_entry"),
    "real_ldif_content": ("tests.conftest_shared", "real_ldif_content"),
    "real_ldif_group_entry": ("tests.conftest", "real_ldif_group_entry"),
    "real_ldif_multiple_entries": ("tests.conftest", "real_ldif_multiple_entries"),
    "real_ldif_user_entry": ("tests.conftest", "real_ldif_user_entry"),
    "rfc_schema_entries": ("tests.integration", "rfc_schema_entries"),
    "rfc_schema_fixture": ("tests.integration", "rfc_schema_fixture"),
    "s": ("flext_ldif", "s"),
    "sample_ldif_entries": ("tests.conftest", "sample_ldif_entries"),
    "schema_service": ("tests.unit", "schema_service"),
    "schema_service_oud": ("tests.unit", "schema_service_oud"),
    "server": ("tests.integration", "server"),
    "services": ("tests.unit", "services"),
    "simple_attribute_definition": ("tests.unit", "simple_attribute_definition"),
    "simple_objectclass_definition": ("tests.unit", "simple_objectclass_definition"),
    "support": ("tests.support", ""),
    "t": ("flext_ldif", "t"),
    "temp_file": ("tests.conftest", "temp_file"),
    "test_create_and_export_entry": (
        "tests.integration",
        "test_create_and_export_entry",
    ),
    "test_ldap_connection": ("tests.integration", "test_ldap_connection"),
    "test_simple_ldap_search": ("tests.integration", "test_simple_ldap_search"),
    "tf": ("tests.test_helpers", "tf"),
    "tk": ("tests.support", "tk"),
    "tm": ("tests.test_helpers", "tm"),
    "tmp_ldif_path": ("tests.integration", "tmp_ldif_path"),
    "tt": ("tests.test_helpers", "tt"),
    "tv": ("tests.test_helpers", "tv"),
    "u": ("tests.utilities", "TestsFlextLdifUtilities"),
    "unique_dn_suffix": ("tests.integration", "unique_dn_suffix"),
    "unit": ("tests.unit", ""),
    "utilities": ("tests.unit", "utilities"),
    "version_module": ("tests.unit", "version_module"),
    "writer": ("tests.integration", "writer"),
    "x": ("flext_ldif", "x"),
}

__all__ = [
    "FIXTURES_DIR",
    "OID_FIXTURES_DIR",
    "APIScenarios",
    "ConfigTestData",
    "FileManager",
    "FlextLdifFixtures",
    "FlextLdifTestConftest",
    "FlextLdifTestFactory",
    "FlextLdifTestsServiceBase",
    "GenericFieldsDict",
    "GetAclAttributesServerType",
    "GetValidValuesType",
    "IsAclAttributeType",
    "IsValidTestType",
    "LdifSample",
    "LdifTestData",
    "MockFlextUtilitiesResultHelpers",
    "MockMatchers",
    "OidTestConstants",
    "TestAclAttributes",
    "TestAclParser",
    "TestAclRoundTripPreservation",
    "TestAliasDiscovery",
    "TestAttributeFixer",
    "TestBoundaryValues",
    "TestCategorizationRealData",
    "TestData",
    "TestDnCaseNormalizationScenarios",
    "TestDnCaseRegistry",
    "TestDnObjectClassMethods",
    "TestEmptyAndMinimalCases",
    "TestEncodingErrors",
    "TestFlextLdifAPIIntegration",
    "TestFlextLdifDeduplicationHelpers",
    "TestFlextLdifFacadeWorkflows",
    "TestFlextLdifModels",
    "TestFlextLdifSettingsIntegration",
    "TestFlextLdifTypesStructure",
    "TestFlextLdifUtilitiesComprehensive",
    "TestIncompleteEntries",
    "TestIntegrationWithLdifFixtures",
    "TestInvalidSchemaDefinitions",
    "TestLargeAndComplexCases",
    "TestLdifParser",
    "TestMalformedLdifHandling",
    "TestMinimalDifferencesOidOud",
    "TestModelsNamespace",
    "TestObjectClassUtilities",
    "TestOidAclMetadataPreservation",
    "TestOidEntryIntegration",
    "TestOidQuirksTransformations",
    "TestOidRoundTripIntegration",
    "TestOidSchemaIntegration",
    "TestOidToOudAclConversion",
    "TestOidToOudIntegrationConversion",
    "TestOidToOudSchemaConversion",
    "TestOudAciMetadataPreservation",
    "TestOudAclIntegration",
    "TestOudEntryIntegration",
    "TestOudMetadataPreservation",
    "TestOudQuirksTransformations",
    "TestOudRoundTripIntegration",
    "TestOudSchemaIntegration",
    "TestOudToOidAclMigration",
    "TestOudToOidEntryMigration",
    "TestOudToOidFullMigration",
    "TestOudToOidSchemaMigration",
    "TestPhase1StandardizationResults",
    "TestQuirksAutoInterchange",
    "TestQuirksConversionMatrixFacade",
    "TestQuirksPropertyValidation",
    "TestQuirksWithRealLdifFixtures",
    "TestRealLdapBatchOperations",
    "TestRealLdapCRUD",
    "TestRealLdapConfigurationFromEnv",
    "TestRealLdapExport",
    "TestRealLdapImport",
    "TestRealLdapRailwayComposition",
    "TestRealLdapRoundtrip",
    "TestRemovalOfOverEngineering",
    "TestRfcDockerRealData",
    "TestRfcExceptionHandlingRealScenarios",
    "TestRfcIntegrationRealWorld",
    "TestRfcParserRealFixtures",
    "TestRfcSchemaParserRealFixtures",
    "TestRfcWriterRealFixtures",
    "TestRoundtripEdgeCases",
    "TestSchemaDeviationsAttributeKeyCasing",
    "TestSchemaDeviationsComplete",
    "TestSchemaDeviationsMissingSpaces",
    "TestSchemaDeviationsNameAliases",
    "TestSchemaDeviationsObsolete",
    "TestSchemaDeviationsOriginalString",
    "TestSchemaDeviationsRoundTrip",
    "TestSchemaDeviationsSpacing",
    "TestSchemaDeviationsSyntaxQuotes",
    "TestSchemaDeviationsUtilities",
    "TestSchemaDeviationsXOrigin",
    "TestSchemaServiceBuilder",
    "TestSchemaServiceCanHandleAttribute",
    "TestSchemaServiceIntegration",
    "TestSchemaServiceParseAttribute",
    "TestSchemaServiceParseObjectClass",
    "TestSchemaServiceRepr",
    "TestSchemaServiceValidateAttribute",
    "TestSchemaServiceValidateObjectClass",
    "TestSchemaServiceWriteAttribute",
    "TestSchemaServiceWriteObjectClass",
    "TestServerTypes",
    "TestSystematicFixtureCoverage",
    "TestUnicodeBoundaries",
    "TestValidators",
    "TestZeroDataLossOidOud",
    "TestsFlextLdifCommonDictionaryTypes",
    "TestsFlextLdifConstants",
    "TestsFlextLdifDnOperationsPure",
    "TestsFlextLdifFixtures",
    "TestsFlextLdifMatchers",
    "TestsFlextLdifMigrationPipeline",
    "TestsFlextLdifMigrationPipelineQuirks",
    "TestsFlextLdifModels",
    "TestsFlextLdifProtocols",
    "TestsFlextLdifQuirksStandardizedConstants",
    "TestsFlextLdifSchemaServiceExecute",
    "TestsFlextLdifTypes",
    "TestsFlextLdifUtilities",
    "TestsFlextLdifValidators",
    "TestsFlextLdifVersion",
    "TestsFlextLdifsFlextLdifWriterDnNormalization",
    "TestsTestFlextLdifAclAttributeRegistry",
    "TestsTestFlextLdifConstants",
    "TestsTestFlextLdifMigrationPipeline",
    "TestsTestFlextLdifProtocols",
    "TestsTestFlextLdifServiceAPIs",
    "ValidateManyType",
    "all_acl_fixtures",
    "all_entries_fixtures",
    "all_integration_fixtures",
    "all_schema_fixtures",
    "api",
    "c",
    "clean_test_ou",
    "complex_attribute_definition",
    "complex_objectclass_definition",
    "constants",
    "conversion_matrix",
    "d",
    "e",
    "fixtures_dir",
    "flext_ldif",
    "h",
    "integration",
    "large_test_dataset",
    "ldap_connection",
    "ldap_container",
    "ldap_container_shared",
    "ldif_parser",
    "ldif_writer",
    "logger",
    "m",
    "make_test_base_dn",
    "make_test_username",
    "migration_inputs",
    "models",
    "oid_acl_fixture",
    "oid_acl_quirk",
    "oid_entries",
    "oid_entries_fixture",
    "oid_integration_fixture",
    "oid_quirk",
    "oid_schema_entries",
    "oid_schema_fixture",
    "oid_schema_quirk",
    "openldap_acl_fixture",
    "openldap_entries",
    "openldap_entries_fixture",
    "openldap_integration_fixture",
    "openldap_schema_entries",
    "openldap_schema_fixture",
    "oud_acl_fixture",
    "oud_acl_quirk",
    "oud_entries",
    "oud_entries_fixture",
    "oud_integration_fixture",
    "oud_quirk",
    "oud_schema_entries",
    "oud_schema_fixture",
    "oud_schema_quirk",
    "p",
    "parametrized_real_data",
    "parser",
    "protocols",
    "pytest_configure",
    "r",
    "real_entry",
    "real_ldif_content",
    "real_ldif_group_entry",
    "real_ldif_multiple_entries",
    "real_ldif_user_entry",
    "rfc_schema_entries",
    "rfc_schema_fixture",
    "s",
    "sample_ldif_entries",
    "schema_service",
    "schema_service_oud",
    "server",
    "services",
    "simple_attribute_definition",
    "simple_objectclass_definition",
    "support",
    "t",
    "temp_file",
    "test_create_and_export_entry",
    "test_ldap_connection",
    "test_simple_ldap_search",
    "tf",
    "tk",
    "tm",
    "tmp_ldif_path",
    "tt",
    "tv",
    "u",
    "unique_dn_suffix",
    "unit",
    "utilities",
    "version_module",
    "writer",
    "x",
]


def __getattr__(name: str) -> FlextTypes.ModuleExport:
    """Lazy-load module attributes on first access (PEP 562)."""
    return lazy_getattr(name, _LAZY_IMPORTS, globals(), __name__)


def __dir__() -> list[str]:
    """Return list of available attributes for dir() and autocomplete."""
    return sorted(__all__)


cleanup_submodule_namespace(__name__, _LAZY_IMPORTS)
