# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Tests package."""

from __future__ import annotations

import typing as _t

from flext_core.lazy import install_lazy_exports, merge_lazy_imports

if _t.TYPE_CHECKING:
    import tests.base as _tests_base

    base = _tests_base
    import tests.conftest as _tests_conftest
    from tests.base import FlextLdifTestsServiceBase, FlextLdifTestsServiceBase as s

    conftest = _tests_conftest
    import tests.conftest_shared as _tests_conftest_shared
    from tests.conftest import (
        FIXTURES_DIR,
        OID_FIXTURES_DIR,
        FlextLdifFixtures,
        flext_ldif,
        ldif_parser,
        ldif_writer,
        pytest_configure,
        real_ldif_group_entry,
        real_ldif_multiple_entries,
        real_ldif_user_entry,
        sample_ldif_entries,
        temp_file,
    )

    conftest_shared = _tests_conftest_shared
    import tests.constants as _tests_constants
    from tests.conftest_shared import (
        large_test_dataset,
        parametrized_real_data,
        real_entry,
        real_ldif_content,
    )

    constants = _tests_constants
    import tests.e2e as _tests_e2e
    from tests.constants import FlextLdifTestConstants, FlextLdifTestConstants as c

    e2e = _tests_e2e
    import tests.helpers as _tests_helpers
    from tests.e2e import test_enterprise

    helpers = _tests_helpers
    import tests.integration as _tests_integration
    from tests.helpers import example_refactoring

    integration = _tests_integration
    import tests.models as _tests_models
    from tests.integration import (
        WORKSPACE_ROOT,
        APIScenarios,
        ConfigTestData,
        TestAclRoundTripPreservation,
        TestBoundaryValues,
        TestCategorizationRealData,
        TestData,
        TestDnCaseNormalizationScenarios,
        TestDnCaseRegistry,
        TestEmptyAndMinimalCases,
        TestEncodingErrors,
        TestFlextLdifAPIIntegration,
        TestFlextLdifFacadeWorkflows,
        TestFlextLdifSettingsIntegration,
        TestIncompleteEntries,
        TestInvalidSchemaDefinitions,
        TestLargeAndComplexCases,
        TestMalformedLdifHandling,
        TestMinimalDifferencesOidOud,
        TestOidAclMetadataPreservation,
        TestOidEntryIntegration,
        TestOidQuirksTransformations,
        TestOidRoundTripIntegration,
        TestOidSchemaIntegration,
        TestOidToOudAclConversion,
        TestOidToOudIntegrationConversion,
        TestOidToOudSchemaConversion,
        TestOudAciMetadataPreservation,
        TestOudAclIntegration,
        TestOudEntryIntegration,
        TestOudMetadataPreservation,
        TestOudQuirksTransformations,
        TestOudRoundTripIntegration,
        TestOudSchemaIntegration,
        TestOudToOidAclMigration,
        TestOudToOidEntryMigration,
        TestOudToOidFullMigration,
        TestOudToOidSchemaMigration,
        TestQuirksConversionMatrixFacade,
        TestQuirksPropertyValidation,
        TestRealLdapBatchOperations,
        TestRealLdapConfigurationFromEnv,
        TestRealLdapCRUD,
        TestRealLdapExport,
        TestRealLdapImport,
        TestRealLdapRailwayComposition,
        TestRealLdapRoundtrip,
        TestRfcDockerRealData,
        TestRfcExceptionHandlingRealScenarios,
        TestRfcIntegrationRealWorld,
        TestRfcParserRealFixtures,
        TestRfcSchemaParserRealFixtures,
        TestRfcWriterRealFixtures,
        TestRoundtripEdgeCases,
        TestSchemaDeviationsAttributeKeyCasing,
        TestSchemaDeviationsComplete,
        TestSchemaDeviationsMissingSpaces,
        TestSchemaDeviationsNameAliases,
        TestSchemaDeviationsObsolete,
        TestSchemaDeviationsOriginalString,
        TestSchemaDeviationsRoundTrip,
        TestSchemaDeviationsSpacing,
        TestSchemaDeviationsSyntaxQuotes,
        TestSchemaDeviationsUtilities,
        TestSchemaDeviationsXOrigin,
        TestsFlextLdifFixtures,
        TestSystematicFixtureCoverage,
        TestUnicodeBoundaries,
        TestZeroDataLossOidOud,
        all_acl_fixtures,
        all_entries_fixtures,
        all_integration_fixtures,
        all_schema_fixtures,
        api,
        clean_test_ou,
        conversion_matrix,
        fixtures_dir,
        ldap_connection,
        ldap_container,
        ldap_container_shared,
        logger,
        make_test_base_dn,
        make_test_username,
        migration_inputs,
        oid_acl_fixture,
        oid_acl_quirk,
        oid_entries,
        oid_entries_fixture,
        oid_integration_fixture,
        oid_quirk,
        oid_schema_entries,
        oid_schema_fixture,
        oid_schema_quirk,
        openldap_acl_fixture,
        openldap_entries,
        openldap_entries_fixture,
        openldap_integration_fixture,
        openldap_schema_entries,
        openldap_schema_fixture,
        oud_acl_fixture,
        oud_acl_quirk,
        oud_entries,
        oud_entries_fixture,
        oud_integration_fixture,
        oud_quirk,
        oud_schema_entries,
        oud_schema_fixture,
        oud_schema_quirk,
        parser,
        rfc_schema_entries,
        rfc_schema_fixture,
        server,
        test_acl_metadata_preservation,
        test_api_integration,
        test_categorization_real_data,
        test_config_integration,
        test_create_and_export_entry,
        test_cross_quirk_conversion,
        test_dn_case_handling,
        test_edge_cases,
        test_error_recovery,
        test_ldap_connection,
        test_ldif_fixtures_integration,
        test_minimal_differences_metadata,
        test_oid_integration,
        test_oud_integration,
        test_oud_to_oid_migration,
        test_pipeline_integration,
        test_quirks_transformations,
        test_real_ldap_config,
        test_real_ldap_crud,
        test_real_ldap_export,
        test_real_ldap_import,
        test_real_ldap_roundtrip,
        test_rfc_docker_real,
        test_rfc_docker_real_integration,
        test_simple_ldap,
        test_simple_ldap_search,
        test_systematic_fixture_coverage,
        test_zero_data_loss_oid_oud,
        test_zero_data_loss_schema,
        tmp_ldif_path,
        unique_dn_suffix,
        writer,
    )

    models = _tests_models
    import tests.protocols as _tests_protocols
    from tests.models import FlextLdifTestModels, FlextLdifTestModels as m

    protocols = _tests_protocols
    import tests.support as _tests_support
    from tests.protocols import FlextLdifTestProtocols, FlextLdifTestProtocols as p

    support = _tests_support
    import tests.test_factory as _tests_test_factory
    from tests.support import (
        FileManager,
        FlextLdifTestConftest,
        FlextLdifTestServiceFactory,
        LdifSample,
        LdifTestData,
        MockFlextUtilitiesResultHelpers,
        MockMatchers,
        TestValidators,
        conftest_factory,
        ldif_data,
        real_services,
        test_files,
        tk,
        validators,
    )

    test_factory = _tests_test_factory
    import tests.test_helpers as _tests_test_helpers
    from tests.test_factory import FlextLdifTestFactory

    test_helpers = _tests_test_helpers
    import tests.typings as _tests_typings
    from tests.test_helpers import (
        TestsFlextLdifMatchers,
        TestsFlextLdifTypes,
        TestsFlextLdifValidators,
        tf,
        tm,
        tt,
        tv,
    )

    typings = _tests_typings
    import tests.unit as _tests_unit
    from tests.typings import (
        FlextLdifTestTypes,
        FlextLdifTestTypes as t,
        GenericFieldsDict,
    )

    unit = _tests_unit
    import tests.unit.services as _tests_unit_services
    from tests.unit import (
        OidTestConstants,
        TestFlextLdifTypesStructure,
        TestIntegrationWithLdifFixtures,
        TestModelsNamespace,
        TestPhase1StandardizationResults,
        TestRemovalOfOverEngineering,
        TestsFlextLdifCommonDictionaryTypes,
        TestsFlextLdifMigrationPipeline,
        TestsFlextLdifMigrationPipelineQuirks,
        test_migration_pipeline,
        test_migration_pipeline_quirks,
        test_typings,
    )
    from tests.unit.__init__ import TestsFlextLdifVersion, test_version
    from tests.unit._utilities.oid import TestFlextLdifUtilitiesOID
    from tests.unit._utilities.parser import TestFlextLdifUtilitiesParser
    from tests.unit._utilities.server import (
        OidServer,
        OudServer,
        TestFlextLdifUtilitiesServer,
    )
    from tests.unit.constants import (
        GetAclAttributesServerType,
        IsAclAttributeType,
        TestsTestFlextLdifAclAttributeRegistry,
        test_acl_registry,
    )
    from tests.unit.protocols import TestsTestFlextLdifProtocols, test_protocols
    from tests.unit.quirks.servers import (
        ACL_TEST_CASES,
        ATTRIBUTE_TEST_CASES,
        ENTRY_TEST_CASES,
        OBJECTCLASS_TEST_CASES,
        AclScenario,
        AclTestCase,
        AttributeScenario,
        AttributeTestCase,
        EntryScenario,
        EntryTestCase,
        ObjectClassScenario,
        ObjectClassTestCase,
        ParseScenario,
        RfcTestHelpers,
        TestDeduplicationHelpers,
        TestNovellAcls,
        TestNovellEntryDetection,
        TestNovellSchemaAttributeDetection,
        TestNovellSchemaAttributeParsing,
        TestNovellSchemaObjectClassDetection,
        TestNovellSchemaObjectClassParsing,
        TestSchemaTransformerNormalizeMatchingRule,
        TestSchemaTransformerNormalizeSyntaxOid,
        TestsFlextLdifEdgeCases,
        TestsFlextLdifNovellInitialization,
        TestsFlextLdifSchemaTransformerNormalizeAttributeName,
        TestsTestFlextLdifApacheQuirks,
        TestsTestFlextLdifDs389Quirks,
        TestsTestFlextLdifOidQuirks,
        TestsTestFlextLdifRelaxedQuirks,
        WriteScenario,
        cleanup_state,
        entry_quirk,
        ldif_api,
        meta_keys,
        novell_server,
        schema_quirk,
    )

    services = _tests_unit_services
    import tests.utilities as _tests_utilities
    from tests.unit.services import (
        TestAliasDiscovery,
        TestQuirksAutoInterchange,
        TestQuirksWithRealLdifFixtures,
        TestsFlextLdifQuirksStandardizedConstants,
        TestsTestFlextLdifMigrationPipeline,
        test_quirks_standardization,
    )
    from tests.unit.utilities import (
        TestAttributeFixer,
        TestDnObjectClassMethods,
        TestFlextLdifUtilitiesComprehensive,
        TestLdifParser,
        TestObjectClassUtilities,
        TestServerTypes,
        TestsFlextLdifDnOperationsPure,
        test_utilities_comprehensive,
        test_utilities_core,
    )

    utilities = _tests_utilities
    from flext_core.decorators import FlextDecorators as d
    from flext_core.exceptions import FlextExceptions as e
    from flext_core.handlers import FlextHandlers as h
    from flext_core.mixins import FlextMixins as x
    from flext_core.result import FlextResult as r
    from tests.utilities import FlextLdifTestUtilities, FlextLdifTestUtilities as u
_LAZY_IMPORTS = merge_lazy_imports(
    (
        "tests.e2e",
        "tests.helpers",
        "tests.integration",
        "tests.support",
        "tests.unit",
    ),
    {
        "FIXTURES_DIR": "tests.conftest",
        "FlextLdifFixtures": "tests.conftest",
        "FlextLdifTestConstants": "tests.constants",
        "FlextLdifTestFactory": "tests.test_factory",
        "FlextLdifTestModels": "tests.models",
        "FlextLdifTestProtocols": "tests.protocols",
        "FlextLdifTestTypes": "tests.typings",
        "FlextLdifTestUtilities": "tests.utilities",
        "FlextLdifTestsServiceBase": "tests.base",
        "GenericFieldsDict": "tests.typings",
        "OID_FIXTURES_DIR": "tests.conftest",
        "TestsFlextLdifMatchers": "tests.test_helpers",
        "TestsFlextLdifTypes": "tests.test_helpers",
        "TestsFlextLdifValidators": "tests.test_helpers",
        "base": "tests.base",
        "c": ("tests.constants", "FlextLdifTestConstants"),
        "conftest": "tests.conftest",
        "conftest_shared": "tests.conftest_shared",
        "constants": "tests.constants",
        "d": ("flext_core.decorators", "FlextDecorators"),
        "e": ("flext_core.exceptions", "FlextExceptions"),
        "e2e": "tests.e2e",
        "flext_ldif": "tests.conftest",
        "h": ("flext_core.handlers", "FlextHandlers"),
        "helpers": "tests.helpers",
        "integration": "tests.integration",
        "large_test_dataset": "tests.conftest_shared",
        "ldif_parser": "tests.conftest",
        "ldif_writer": "tests.conftest",
        "m": ("tests.models", "FlextLdifTestModels"),
        "models": "tests.models",
        "p": ("tests.protocols", "FlextLdifTestProtocols"),
        "parametrized_real_data": "tests.conftest_shared",
        "protocols": "tests.protocols",
        "pytest_configure": "tests.conftest",
        "r": ("flext_core.result", "FlextResult"),
        "real_entry": "tests.conftest_shared",
        "real_ldif_content": "tests.conftest_shared",
        "real_ldif_group_entry": "tests.conftest",
        "real_ldif_multiple_entries": "tests.conftest",
        "real_ldif_user_entry": "tests.conftest",
        "s": ("tests.base", "FlextLdifTestsServiceBase"),
        "sample_ldif_entries": "tests.conftest",
        "support": "tests.support",
        "t": ("tests.typings", "FlextLdifTestTypes"),
        "temp_file": "tests.conftest",
        "test_factory": "tests.test_factory",
        "test_helpers": "tests.test_helpers",
        "tf": "tests.test_helpers",
        "tm": "tests.test_helpers",
        "tt": "tests.test_helpers",
        "tv": "tests.test_helpers",
        "typings": "tests.typings",
        "u": ("tests.utilities", "FlextLdifTestUtilities"),
        "unit": "tests.unit",
        "utilities": "tests.utilities",
        "x": ("flext_core.mixins", "FlextMixins"),
    },
)

__all__ = [
    "ACL_TEST_CASES",
    "ATTRIBUTE_TEST_CASES",
    "ENTRY_TEST_CASES",
    "FIXTURES_DIR",
    "OBJECTCLASS_TEST_CASES",
    "OID_FIXTURES_DIR",
    "WORKSPACE_ROOT",
    "APIScenarios",
    "AclScenario",
    "AclTestCase",
    "AttributeScenario",
    "AttributeTestCase",
    "ConfigTestData",
    "EntryScenario",
    "EntryTestCase",
    "FileManager",
    "FlextLdifFixtures",
    "FlextLdifTestConftest",
    "FlextLdifTestConstants",
    "FlextLdifTestFactory",
    "FlextLdifTestModels",
    "FlextLdifTestProtocols",
    "FlextLdifTestServiceFactory",
    "FlextLdifTestTypes",
    "FlextLdifTestUtilities",
    "FlextLdifTestsServiceBase",
    "GenericFieldsDict",
    "GetAclAttributesServerType",
    "IsAclAttributeType",
    "LdifSample",
    "LdifTestData",
    "MockFlextUtilitiesResultHelpers",
    "MockMatchers",
    "ObjectClassScenario",
    "ObjectClassTestCase",
    "OidServer",
    "OidTestConstants",
    "OudServer",
    "ParseScenario",
    "RfcTestHelpers",
    "TestAclRoundTripPreservation",
    "TestAliasDiscovery",
    "TestAttributeFixer",
    "TestBoundaryValues",
    "TestCategorizationRealData",
    "TestData",
    "TestDeduplicationHelpers",
    "TestDnCaseNormalizationScenarios",
    "TestDnCaseRegistry",
    "TestDnObjectClassMethods",
    "TestEmptyAndMinimalCases",
    "TestEncodingErrors",
    "TestFlextLdifAPIIntegration",
    "TestFlextLdifFacadeWorkflows",
    "TestFlextLdifSettingsIntegration",
    "TestFlextLdifTypesStructure",
    "TestFlextLdifUtilitiesComprehensive",
    "TestFlextLdifUtilitiesOID",
    "TestFlextLdifUtilitiesParser",
    "TestFlextLdifUtilitiesServer",
    "TestIncompleteEntries",
    "TestIntegrationWithLdifFixtures",
    "TestInvalidSchemaDefinitions",
    "TestLargeAndComplexCases",
    "TestLdifParser",
    "TestMalformedLdifHandling",
    "TestMinimalDifferencesOidOud",
    "TestModelsNamespace",
    "TestNovellAcls",
    "TestNovellEntryDetection",
    "TestNovellSchemaAttributeDetection",
    "TestNovellSchemaAttributeParsing",
    "TestNovellSchemaObjectClassDetection",
    "TestNovellSchemaObjectClassParsing",
    "TestObjectClassUtilities",
    "TestOidAclMetadataPreservation",
    "TestOidEntryIntegration",
    "TestOidQuirksTransformations",
    "TestOidRoundTripIntegration",
    "TestOidSchemaIntegration",
    "TestOidToOudAclConversion",
    "TestOidToOudIntegrationConversion",
    "TestOidToOudSchemaConversion",
    "TestOudAciMetadataPreservation",
    "TestOudAclIntegration",
    "TestOudEntryIntegration",
    "TestOudMetadataPreservation",
    "TestOudQuirksTransformations",
    "TestOudRoundTripIntegration",
    "TestOudSchemaIntegration",
    "TestOudToOidAclMigration",
    "TestOudToOidEntryMigration",
    "TestOudToOidFullMigration",
    "TestOudToOidSchemaMigration",
    "TestPhase1StandardizationResults",
    "TestQuirksAutoInterchange",
    "TestQuirksConversionMatrixFacade",
    "TestQuirksPropertyValidation",
    "TestQuirksWithRealLdifFixtures",
    "TestRealLdapBatchOperations",
    "TestRealLdapCRUD",
    "TestRealLdapConfigurationFromEnv",
    "TestRealLdapExport",
    "TestRealLdapImport",
    "TestRealLdapRailwayComposition",
    "TestRealLdapRoundtrip",
    "TestRemovalOfOverEngineering",
    "TestRfcDockerRealData",
    "TestRfcExceptionHandlingRealScenarios",
    "TestRfcIntegrationRealWorld",
    "TestRfcParserRealFixtures",
    "TestRfcSchemaParserRealFixtures",
    "TestRfcWriterRealFixtures",
    "TestRoundtripEdgeCases",
    "TestSchemaDeviationsAttributeKeyCasing",
    "TestSchemaDeviationsComplete",
    "TestSchemaDeviationsMissingSpaces",
    "TestSchemaDeviationsNameAliases",
    "TestSchemaDeviationsObsolete",
    "TestSchemaDeviationsOriginalString",
    "TestSchemaDeviationsRoundTrip",
    "TestSchemaDeviationsSpacing",
    "TestSchemaDeviationsSyntaxQuotes",
    "TestSchemaDeviationsUtilities",
    "TestSchemaDeviationsXOrigin",
    "TestSchemaTransformerNormalizeMatchingRule",
    "TestSchemaTransformerNormalizeSyntaxOid",
    "TestServerTypes",
    "TestSystematicFixtureCoverage",
    "TestUnicodeBoundaries",
    "TestValidators",
    "TestZeroDataLossOidOud",
    "TestsFlextLdifCommonDictionaryTypes",
    "TestsFlextLdifDnOperationsPure",
    "TestsFlextLdifEdgeCases",
    "TestsFlextLdifFixtures",
    "TestsFlextLdifMatchers",
    "TestsFlextLdifMigrationPipeline",
    "TestsFlextLdifMigrationPipelineQuirks",
    "TestsFlextLdifNovellInitialization",
    "TestsFlextLdifQuirksStandardizedConstants",
    "TestsFlextLdifSchemaTransformerNormalizeAttributeName",
    "TestsFlextLdifTypes",
    "TestsFlextLdifValidators",
    "TestsFlextLdifVersion",
    "TestsTestFlextLdifAclAttributeRegistry",
    "TestsTestFlextLdifApacheQuirks",
    "TestsTestFlextLdifDs389Quirks",
    "TestsTestFlextLdifMigrationPipeline",
    "TestsTestFlextLdifOidQuirks",
    "TestsTestFlextLdifProtocols",
    "TestsTestFlextLdifRelaxedQuirks",
    "WriteScenario",
    "all_acl_fixtures",
    "all_entries_fixtures",
    "all_integration_fixtures",
    "all_schema_fixtures",
    "api",
    "base",
    "c",
    "clean_test_ou",
    "cleanup_state",
    "conftest",
    "conftest_factory",
    "conftest_shared",
    "constants",
    "conversion_matrix",
    "d",
    "e",
    "e2e",
    "entry_quirk",
    "example_refactoring",
    "fixtures_dir",
    "flext_ldif",
    "h",
    "helpers",
    "integration",
    "large_test_dataset",
    "ldap_connection",
    "ldap_container",
    "ldap_container_shared",
    "ldif_api",
    "ldif_data",
    "ldif_parser",
    "ldif_writer",
    "logger",
    "m",
    "make_test_base_dn",
    "make_test_username",
    "meta_keys",
    "migration_inputs",
    "models",
    "novell_server",
    "oid_acl_fixture",
    "oid_acl_quirk",
    "oid_entries",
    "oid_entries_fixture",
    "oid_integration_fixture",
    "oid_quirk",
    "oid_schema_entries",
    "oid_schema_fixture",
    "oid_schema_quirk",
    "openldap_acl_fixture",
    "openldap_entries",
    "openldap_entries_fixture",
    "openldap_integration_fixture",
    "openldap_schema_entries",
    "openldap_schema_fixture",
    "oud_acl_fixture",
    "oud_acl_quirk",
    "oud_entries",
    "oud_entries_fixture",
    "oud_integration_fixture",
    "oud_quirk",
    "oud_schema_entries",
    "oud_schema_fixture",
    "oud_schema_quirk",
    "p",
    "parametrized_real_data",
    "parser",
    "protocols",
    "pytest_configure",
    "r",
    "real_entry",
    "real_ldif_content",
    "real_ldif_group_entry",
    "real_ldif_multiple_entries",
    "real_ldif_user_entry",
    "real_services",
    "rfc_schema_entries",
    "rfc_schema_fixture",
    "s",
    "sample_ldif_entries",
    "schema_quirk",
    "server",
    "services",
    "support",
    "t",
    "temp_file",
    "test_acl_metadata_preservation",
    "test_acl_registry",
    "test_api_integration",
    "test_categorization_real_data",
    "test_config_integration",
    "test_create_and_export_entry",
    "test_cross_quirk_conversion",
    "test_dn_case_handling",
    "test_edge_cases",
    "test_enterprise",
    "test_error_recovery",
    "test_factory",
    "test_files",
    "test_helpers",
    "test_ldap_connection",
    "test_ldif_fixtures_integration",
    "test_migration_pipeline",
    "test_migration_pipeline_quirks",
    "test_minimal_differences_metadata",
    "test_oid_integration",
    "test_oud_integration",
    "test_oud_to_oid_migration",
    "test_pipeline_integration",
    "test_protocols",
    "test_quirks_standardization",
    "test_quirks_transformations",
    "test_real_ldap_config",
    "test_real_ldap_crud",
    "test_real_ldap_export",
    "test_real_ldap_import",
    "test_real_ldap_roundtrip",
    "test_rfc_docker_real",
    "test_rfc_docker_real_integration",
    "test_simple_ldap",
    "test_simple_ldap_search",
    "test_systematic_fixture_coverage",
    "test_typings",
    "test_utilities_comprehensive",
    "test_utilities_core",
    "test_version",
    "test_zero_data_loss_oid_oud",
    "test_zero_data_loss_schema",
    "tf",
    "tk",
    "tm",
    "tmp_ldif_path",
    "tt",
    "tv",
    "typings",
    "u",
    "unique_dn_suffix",
    "unit",
    "utilities",
    "validators",
    "writer",
    "x",
]


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS)
