# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Integration package."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import TYPE_CHECKING as _TYPE_CHECKING

from flext_core.lazy import install_lazy_exports

if _TYPE_CHECKING:
    from flext_core import FlextTypes
    from flext_core.constants import FlextConstants as c
    from flext_core.decorators import FlextDecorators as d
    from flext_core.exceptions import FlextExceptions as e
    from flext_core.handlers import FlextHandlers as h
    from flext_core.mixins import FlextMixins as x
    from flext_core.models import FlextModels as m
    from flext_core.protocols import FlextProtocols as p
    from flext_core.result import FlextResult as r
    from flext_core.service import FlextService as s
    from flext_core.typings import FlextTypes as t
    from flext_core.utilities import FlextUtilities as u
    from flext_ldif import (
        conftest,
        test_acl_metadata_preservation,
        test_api_integration,
        test_categorization_real_data,
        test_config_integration,
        test_cross_quirk_conversion,
        test_dn_case_handling,
        test_edge_cases,
        test_error_recovery,
        test_ldif_fixtures_integration,
        test_minimal_differences_metadata,
        test_oid_integration,
        test_oud_integration,
        test_oud_to_oid_migration,
        test_pipeline_integration,
        test_quirks_transformations,
        test_real_ldap_config,
        test_real_ldap_crud,
        test_real_ldap_export,
        test_real_ldap_import,
        test_real_ldap_roundtrip,
        test_rfc_docker_real,
        test_rfc_docker_real_integration,
        test_simple_ldap,
        test_systematic_fixture_coverage,
        test_zero_data_loss_oid_oud,
        test_zero_data_loss_schema,
        typings,
    )
    from flext_ldif.conftest import (
        WORKSPACE_ROOT,
        all_acl_fixtures,
        all_entries_fixtures,
        all_integration_fixtures,
        all_schema_fixtures,
        auto_bind,
        bind_dn,
        bind_ok,
        clean_test_ou,
        conn,
        conversion_matrix,
        dns_to_delete,
        dns_to_delete2,
        entries,
        entries2,
        ldap_connection,
        ldap_container,
        ldap_container_shared,
        make_test_base_dn,
        make_test_username,
        oid_acl_fixture,
        oid_acl_quirk,
        oid_entries,
        oid_entries_fixture,
        oid_integration_fixture,
        oid_quirk,
        oid_schema_entries,
        oid_schema_fixture,
        oid_schema_quirk,
        openldap_acl_fixture,
        openldap_entries,
        openldap_entries_fixture,
        openldap_integration_fixture,
        openldap_schema_entries,
        openldap_schema_fixture,
        oud_acl_fixture,
        oud_acl_quirk,
        oud_entries,
        oud_entries_fixture,
        oud_integration_fixture,
        oud_quirk,
        oud_schema_entries,
        oud_schema_fixture,
        oud_schema_quirk,
        parser,
        password,
        rfc_schema_entries,
        rfc_schema_fixture,
        server,
        server_url,
        srv,
        test_ou_dn,
        tmp_ldif_path,
        unique_dn_suffix,
        user,
        writer,
    )
    from flext_ldif.test_api_integration import APIScenarios
    from flext_ldif.test_categorization_real_data import (
        TestCategorizationRealData,
        attr_line,
        cat_entries,
        categories,
        category_header,
        entry_line,
        filtered,
        filtered_line,
        include_attributes,
        rejected,
        rejected_line,
        stats,
    )
    from flext_ldif.test_config_integration import ConfigTestData, logger
    from flext_ldif.test_cross_quirk_conversion import (
        CROSS_QUIRK_CONVERSION_CONSTANTS,
        CrossQuirkConversionConstants,
        TestOidToOudSchemaConversion,
    )
    from flext_ldif.test_dn_case_handling import (
        TestDnCaseNormalizationScenarios,
        TestDnCaseRegistry,
    )
    from flext_ldif.test_edge_cases import TestEmptyAndMinimalCases
    from flext_ldif.test_error_recovery import TestMalformedLdifHandling
    from flext_ldif.test_ldif_fixtures_integration import TestsFlextLdifFixtures
    from flext_ldif.test_minimal_differences_metadata import (
        TestMinimalDifferencesOidOud,
    )
    from flext_ldif.test_oid_integration import TestOidSchemaIntegration
    from flext_ldif.test_oud_integration import TestOudSchemaIntegration
    from flext_ldif.test_oud_to_oid_migration import TestOudToOidSchemaMigration
    from flext_ldif.test_pipeline_integration import TestFlextLdifFacadeWorkflows
    from flext_ldif.test_quirks_transformations import (
        TestOidQuirksTransformations,
        base_dir,
        fixtures_dir,
        migration_inputs,
        oid_input_dir,
        oud_input_dir,
    )
    from flext_ldif.test_real_ldap_config import (
        TestRealLdapConfigurationFromEnv,
        TestRealLdapRailwayComposition,
    )
    from flext_ldif.test_real_ldap_crud import (
        TestRealLdapBatchOperations,
        TestRealLdapCRUD,
    )
    from flext_ldif.test_real_ldap_export import TestRealLdapExport
    from flext_ldif.test_real_ldap_import import TestRealLdapImport
    from flext_ldif.test_real_ldap_roundtrip import TestRealLdapRoundtrip
    from flext_ldif.test_rfc_docker_real import TestRfcDockerRealData
    from flext_ldif.test_rfc_docker_real_integration import TestRfcParserRealFixtures
    from flext_ldif.test_simple_ldap import (
        api,
        attributes,
        attrs,
        base_dn,
        dn,
        entry_result,
        flext_entry,
        ldap_entry,
        ldif_output,
        result,
        search_scope,
        test_create_and_export_entry,
        test_dn,
        test_ldap_connection,
        unique_username,
        write_result,
    )
    from flext_ldif.test_systematic_fixture_coverage import (
        TestSystematicFixtureCoverage,
    )
    from flext_ldif.test_zero_data_loss_schema import TestSchemaDeviationsSyntaxQuotes

_LAZY_IMPORTS: FlextTypes.LazyImportIndex = {
    "APIScenarios": "flext_ldif.test_api_integration",
    "CROSS_QUIRK_CONVERSION_CONSTANTS": "flext_ldif.test_cross_quirk_conversion",
    "ConfigTestData": "flext_ldif.test_config_integration",
    "CrossQuirkConversionConstants": "flext_ldif.test_cross_quirk_conversion",
    "TestCategorizationRealData": "flext_ldif.test_categorization_real_data",
    "TestDnCaseNormalizationScenarios": "flext_ldif.test_dn_case_handling",
    "TestDnCaseRegistry": "flext_ldif.test_dn_case_handling",
    "TestEmptyAndMinimalCases": "flext_ldif.test_edge_cases",
    "TestFlextLdifFacadeWorkflows": "flext_ldif.test_pipeline_integration",
    "TestMalformedLdifHandling": "flext_ldif.test_error_recovery",
    "TestMinimalDifferencesOidOud": "flext_ldif.test_minimal_differences_metadata",
    "TestOidQuirksTransformations": "flext_ldif.test_quirks_transformations",
    "TestOidSchemaIntegration": "flext_ldif.test_oid_integration",
    "TestOidToOudSchemaConversion": "flext_ldif.test_cross_quirk_conversion",
    "TestOudSchemaIntegration": "flext_ldif.test_oud_integration",
    "TestOudToOidSchemaMigration": "flext_ldif.test_oud_to_oid_migration",
    "TestRealLdapBatchOperations": "flext_ldif.test_real_ldap_crud",
    "TestRealLdapCRUD": "flext_ldif.test_real_ldap_crud",
    "TestRealLdapConfigurationFromEnv": "flext_ldif.test_real_ldap_config",
    "TestRealLdapExport": "flext_ldif.test_real_ldap_export",
    "TestRealLdapImport": "flext_ldif.test_real_ldap_import",
    "TestRealLdapRailwayComposition": "flext_ldif.test_real_ldap_config",
    "TestRealLdapRoundtrip": "flext_ldif.test_real_ldap_roundtrip",
    "TestRfcDockerRealData": "flext_ldif.test_rfc_docker_real",
    "TestRfcParserRealFixtures": "flext_ldif.test_rfc_docker_real_integration",
    "TestSchemaDeviationsSyntaxQuotes": "flext_ldif.test_zero_data_loss_schema",
    "TestSystematicFixtureCoverage": "flext_ldif.test_systematic_fixture_coverage",
    "TestsFlextLdifFixtures": "flext_ldif.test_ldif_fixtures_integration",
    "WORKSPACE_ROOT": "flext_ldif.conftest",
    "all_acl_fixtures": "flext_ldif.conftest",
    "all_entries_fixtures": "flext_ldif.conftest",
    "all_integration_fixtures": "flext_ldif.conftest",
    "all_schema_fixtures": "flext_ldif.conftest",
    "api": "flext_ldif.test_simple_ldap",
    "attr_line": "flext_ldif.test_categorization_real_data",
    "attributes": "flext_ldif.test_simple_ldap",
    "attrs": "flext_ldif.test_simple_ldap",
    "auto_bind": "flext_ldif.conftest",
    "base_dir": "flext_ldif.test_quirks_transformations",
    "base_dn": "flext_ldif.test_simple_ldap",
    "bind_dn": "flext_ldif.conftest",
    "bind_ok": "flext_ldif.conftest",
    "c": ("flext_core.constants", "FlextConstants"),
    "cat_entries": "flext_ldif.test_categorization_real_data",
    "categories": "flext_ldif.test_categorization_real_data",
    "category_header": "flext_ldif.test_categorization_real_data",
    "clean_test_ou": "flext_ldif.conftest",
    "conftest": "flext_ldif.conftest",
    "conn": "flext_ldif.conftest",
    "conversion_matrix": "flext_ldif.conftest",
    "d": ("flext_core.decorators", "FlextDecorators"),
    "dn": "flext_ldif.test_simple_ldap",
    "dns_to_delete": "flext_ldif.conftest",
    "dns_to_delete2": "flext_ldif.conftest",
    "e": ("flext_core.exceptions", "FlextExceptions"),
    "entries": "flext_ldif.conftest",
    "entries2": "flext_ldif.conftest",
    "entry_line": "flext_ldif.test_categorization_real_data",
    "entry_result": "flext_ldif.test_simple_ldap",
    "filtered": "flext_ldif.test_categorization_real_data",
    "filtered_line": "flext_ldif.test_categorization_real_data",
    "fixtures_dir": "flext_ldif.test_quirks_transformations",
    "flext_entry": "flext_ldif.test_simple_ldap",
    "h": ("flext_core.handlers", "FlextHandlers"),
    "include_attributes": "flext_ldif.test_categorization_real_data",
    "ldap_connection": "flext_ldif.conftest",
    "ldap_container": "flext_ldif.conftest",
    "ldap_container_shared": "flext_ldif.conftest",
    "ldap_entry": "flext_ldif.test_simple_ldap",
    "ldif_output": "flext_ldif.test_simple_ldap",
    "logger": "flext_ldif.test_config_integration",
    "m": ("flext_core.models", "FlextModels"),
    "make_test_base_dn": "flext_ldif.conftest",
    "make_test_username": "flext_ldif.conftest",
    "migration_inputs": "flext_ldif.test_quirks_transformations",
    "oid_acl_fixture": "flext_ldif.conftest",
    "oid_acl_quirk": "flext_ldif.conftest",
    "oid_entries": "flext_ldif.conftest",
    "oid_entries_fixture": "flext_ldif.conftest",
    "oid_input_dir": "flext_ldif.test_quirks_transformations",
    "oid_integration_fixture": "flext_ldif.conftest",
    "oid_quirk": "flext_ldif.conftest",
    "oid_schema_entries": "flext_ldif.conftest",
    "oid_schema_fixture": "flext_ldif.conftest",
    "oid_schema_quirk": "flext_ldif.conftest",
    "openldap_acl_fixture": "flext_ldif.conftest",
    "openldap_entries": "flext_ldif.conftest",
    "openldap_entries_fixture": "flext_ldif.conftest",
    "openldap_integration_fixture": "flext_ldif.conftest",
    "openldap_schema_entries": "flext_ldif.conftest",
    "openldap_schema_fixture": "flext_ldif.conftest",
    "oud_acl_fixture": "flext_ldif.conftest",
    "oud_acl_quirk": "flext_ldif.conftest",
    "oud_entries": "flext_ldif.conftest",
    "oud_entries_fixture": "flext_ldif.conftest",
    "oud_input_dir": "flext_ldif.test_quirks_transformations",
    "oud_integration_fixture": "flext_ldif.conftest",
    "oud_quirk": "flext_ldif.conftest",
    "oud_schema_entries": "flext_ldif.conftest",
    "oud_schema_fixture": "flext_ldif.conftest",
    "oud_schema_quirk": "flext_ldif.conftest",
    "p": ("flext_core.protocols", "FlextProtocols"),
    "parser": "flext_ldif.conftest",
    "password": "flext_ldif.conftest",
    "r": ("flext_core.result", "FlextResult"),
    "rejected": "flext_ldif.test_categorization_real_data",
    "rejected_line": "flext_ldif.test_categorization_real_data",
    "result": "flext_ldif.test_simple_ldap",
    "rfc_schema_entries": "flext_ldif.conftest",
    "rfc_schema_fixture": "flext_ldif.conftest",
    "s": ("flext_core.service", "FlextService"),
    "search_scope": "flext_ldif.test_simple_ldap",
    "server": "flext_ldif.conftest",
    "server_url": "flext_ldif.conftest",
    "srv": "flext_ldif.conftest",
    "stats": "flext_ldif.test_categorization_real_data",
    "t": ("flext_core.typings", "FlextTypes"),
    "test_acl_metadata_preservation": "flext_ldif.test_acl_metadata_preservation",
    "test_api_integration": "flext_ldif.test_api_integration",
    "test_categorization_real_data": "flext_ldif.test_categorization_real_data",
    "test_config_integration": "flext_ldif.test_config_integration",
    "test_create_and_export_entry": "flext_ldif.test_simple_ldap",
    "test_cross_quirk_conversion": "flext_ldif.test_cross_quirk_conversion",
    "test_dn": "flext_ldif.test_simple_ldap",
    "test_dn_case_handling": "flext_ldif.test_dn_case_handling",
    "test_edge_cases": "flext_ldif.test_edge_cases",
    "test_error_recovery": "flext_ldif.test_error_recovery",
    "test_ldap_connection": "flext_ldif.test_simple_ldap",
    "test_ldif_fixtures_integration": "flext_ldif.test_ldif_fixtures_integration",
    "test_minimal_differences_metadata": "flext_ldif.test_minimal_differences_metadata",
    "test_oid_integration": "flext_ldif.test_oid_integration",
    "test_ou_dn": "flext_ldif.conftest",
    "test_oud_integration": "flext_ldif.test_oud_integration",
    "test_oud_to_oid_migration": "flext_ldif.test_oud_to_oid_migration",
    "test_pipeline_integration": "flext_ldif.test_pipeline_integration",
    "test_quirks_transformations": "flext_ldif.test_quirks_transformations",
    "test_real_ldap_config": "flext_ldif.test_real_ldap_config",
    "test_real_ldap_crud": "flext_ldif.test_real_ldap_crud",
    "test_real_ldap_export": "flext_ldif.test_real_ldap_export",
    "test_real_ldap_import": "flext_ldif.test_real_ldap_import",
    "test_real_ldap_roundtrip": "flext_ldif.test_real_ldap_roundtrip",
    "test_rfc_docker_real": "flext_ldif.test_rfc_docker_real",
    "test_rfc_docker_real_integration": "flext_ldif.test_rfc_docker_real_integration",
    "test_simple_ldap": "flext_ldif.test_simple_ldap",
    "test_systematic_fixture_coverage": "flext_ldif.test_systematic_fixture_coverage",
    "test_zero_data_loss_oid_oud": "flext_ldif.test_zero_data_loss_oid_oud",
    "test_zero_data_loss_schema": "flext_ldif.test_zero_data_loss_schema",
    "tmp_ldif_path": "flext_ldif.conftest",
    "typings": "flext_ldif.typings",
    "u": ("flext_core.utilities", "FlextUtilities"),
    "unique_dn_suffix": "flext_ldif.conftest",
    "unique_username": "flext_ldif.test_simple_ldap",
    "user": "flext_ldif.conftest",
    "write_result": "flext_ldif.test_simple_ldap",
    "writer": "flext_ldif.conftest",
    "x": ("flext_core.mixins", "FlextMixins"),
}


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS)
