# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make codegen
#
"""Integration tests for FLEXT-LDIF service interactions.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT

"""

from __future__ import annotations

from typing import TYPE_CHECKING

from flext_core.lazy import cleanup_submodule_namespace, lazy_getattr

if TYPE_CHECKING:
    from flext_core.typings import FlextTypes

    from tests.integration.conftest import (
        LDAP_ADMIN_DN,
        LDAP_ADMIN_PASSWORD,
        LDAP_BASE_DN,
        LDAP_COMPOSE_FILE,
        LDAP_CONTAINER_NAME,
        LDAP_PORT,
        LDAP_SERVICE_NAME,
        WORKSPACE_ROOT,
        all_acl_fixtures,
        all_entries_fixtures,
        all_integration_fixtures,
        all_schema_fixtures,
        api,
        clean_test_ou,
        conversion_matrix,
        ldap_connection,
        ldap_container,
        ldap_container_shared,
        make_test_base_dn,
        make_test_username,
        oid_acl_fixture,
        oid_acl_quirk,
        oid_entries,
        oid_entries_fixture,
        oid_integration_fixture,
        oid_quirk,
        oid_schema_entries,
        oid_schema_fixture,
        oid_schema_quirk,
        openldap_acl_fixture,
        openldap_entries,
        openldap_entries_fixture,
        openldap_integration_fixture,
        openldap_schema_entries,
        openldap_schema_fixture,
        oud_acl_fixture,
        oud_acl_quirk,
        oud_entries,
        oud_entries_fixture,
        oud_integration_fixture,
        oud_quirk,
        oud_schema_entries,
        oud_schema_fixture,
        oud_schema_quirk,
        parser,
        rfc_schema_entries,
        rfc_schema_fixture,
        server,
        tmp_ldif_path,
        unique_dn_suffix,
        writer,
    )
    from tests.integration.test_acl_metadata_preservation import (
        TestAclRoundTripPreservation,
        TestOidAclMetadataPreservation,
        TestOudAciMetadataPreservation,
    )
    from tests.integration.test_api_integration import (
        APIScenarios,
        TestData,
        TestFlextLdifAPIIntegration,
    )
    from tests.integration.test_categorization_real_data import (
        TestCategorizationRealData,
    )
    from tests.integration.test_config_integration import (
        ConfigTestData,
        TestFlextLdifSettingsIntegration,
        logger,
    )
    from tests.integration.test_cross_quirk_conversion import (
        TestOidToOudAclConversion,
        TestOidToOudIntegrationConversion,
        TestOidToOudSchemaConversion,
        TestQuirksConversionMatrixFacade,
    )
    from tests.integration.test_dn_case_handling import (
        TestDnCaseNormalizationScenarios,
        TestDnCaseRegistry,
    )
    from tests.integration.test_edge_cases import (
        TestBoundaryValues,
        TestEmptyAndMinimalCases,
        TestLargeAndComplexCases,
        TestRoundtripEdgeCases,
        TestUnicodeBoundaries,
    )
    from tests.integration.test_error_recovery import (
        TestEncodingErrors,
        TestIncompleteEntries,
        TestInvalidSchemaDefinitions,
        TestMalformedLdifHandling,
    )
    from tests.integration.test_ldif_fixtures_integration import TestsFlextLdifFixtures
    from tests.integration.test_minimal_differences_metadata import (
        TestMinimalDifferencesOidOud,
    )
    from tests.integration.test_oid_integration import (
        TestOidEntryIntegration,
        TestOidRoundTripIntegration,
        TestOidSchemaIntegration,
    )
    from tests.integration.test_oud_integration import (
        TestOudAclIntegration,
        TestOudEntryIntegration,
        TestOudMetadataPreservation,
        TestOudRoundTripIntegration,
        TestOudSchemaIntegration,
    )
    from tests.integration.test_oud_to_oid_migration import (
        TestOudToOidAclMigration,
        TestOudToOidEntryMigration,
        TestOudToOidFullMigration,
        TestOudToOidSchemaMigration,
    )
    from tests.integration.test_pipeline_integration import TestFlextLdifFacadeWorkflows
    from tests.integration.test_quirks_transformations import (
        TestOidQuirksTransformations,
        TestOudQuirksTransformations,
        TestQuirksPropertyValidation,
        fixtures_dir,
        migration_inputs,
    )
    from tests.integration.test_real_ldap_config import (
        TestRealLdapConfigurationFromEnv,
        TestRealLdapRailwayComposition,
    )
    from tests.integration.test_real_ldap_crud import (
        TestRealLdapBatchOperations,
        TestRealLdapCRUD,
    )
    from tests.integration.test_real_ldap_export import TestRealLdapExport
    from tests.integration.test_real_ldap_import import TestRealLdapImport
    from tests.integration.test_real_ldap_roundtrip import TestRealLdapRoundtrip
    from tests.integration.test_rfc_docker_real import (
        TestRfcDockerRealData,
        TestRfcIntegrationRealWorld,
    )
    from tests.integration.test_rfc_docker_real_integration import (
        TestRfcExceptionHandlingRealScenarios,
        TestRfcParserRealFixtures,
        TestRfcSchemaParserRealFixtures,
        TestRfcWriterRealFixtures,
    )
    from tests.integration.test_simple_ldap import (
        test_create_and_export_entry,
        test_ldap_connection,
        test_simple_ldap_search,
    )
    from tests.integration.test_systematic_fixture_coverage import (
        TestSystematicFixtureCoverage,
    )
    from tests.integration.test_zero_data_loss_oid_oud import TestZeroDataLossOidOud
    from tests.integration.test_zero_data_loss_schema import (
        TestSchemaDeviationsAttributeKeyCasing,
        TestSchemaDeviationsComplete,
        TestSchemaDeviationsMissingSpaces,
        TestSchemaDeviationsNameAliases,
        TestSchemaDeviationsObsolete,
        TestSchemaDeviationsOriginalString,
        TestSchemaDeviationsRoundTrip,
        TestSchemaDeviationsSpacing,
        TestSchemaDeviationsSyntaxQuotes,
        TestSchemaDeviationsUtilities,
        TestSchemaDeviationsUtilities as u,
        TestSchemaDeviationsXOrigin,
    )

# Lazy import mapping: export_name -> (module_path, attr_name)
_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    "APIScenarios": ("tests.integration.test_api_integration", "APIScenarios"),
    "ConfigTestData": ("tests.integration.test_config_integration", "ConfigTestData"),
    "LDAP_ADMIN_DN": ("tests.integration.conftest", "LDAP_ADMIN_DN"),
    "LDAP_ADMIN_PASSWORD": ("tests.integration.conftest", "LDAP_ADMIN_PASSWORD"),
    "LDAP_BASE_DN": ("tests.integration.conftest", "LDAP_BASE_DN"),
    "LDAP_COMPOSE_FILE": ("tests.integration.conftest", "LDAP_COMPOSE_FILE"),
    "LDAP_CONTAINER_NAME": ("tests.integration.conftest", "LDAP_CONTAINER_NAME"),
    "LDAP_PORT": ("tests.integration.conftest", "LDAP_PORT"),
    "LDAP_SERVICE_NAME": ("tests.integration.conftest", "LDAP_SERVICE_NAME"),
    "TestAclRoundTripPreservation": ("tests.integration.test_acl_metadata_preservation", "TestAclRoundTripPreservation"),
    "TestBoundaryValues": ("tests.integration.test_edge_cases", "TestBoundaryValues"),
    "TestCategorizationRealData": ("tests.integration.test_categorization_real_data", "TestCategorizationRealData"),
    "TestData": ("tests.integration.test_api_integration", "TestData"),
    "TestDnCaseNormalizationScenarios": ("tests.integration.test_dn_case_handling", "TestDnCaseNormalizationScenarios"),
    "TestDnCaseRegistry": ("tests.integration.test_dn_case_handling", "TestDnCaseRegistry"),
    "TestEmptyAndMinimalCases": ("tests.integration.test_edge_cases", "TestEmptyAndMinimalCases"),
    "TestEncodingErrors": ("tests.integration.test_error_recovery", "TestEncodingErrors"),
    "TestFlextLdifAPIIntegration": ("tests.integration.test_api_integration", "TestFlextLdifAPIIntegration"),
    "TestFlextLdifFacadeWorkflows": ("tests.integration.test_pipeline_integration", "TestFlextLdifFacadeWorkflows"),
    "TestFlextLdifSettingsIntegration": ("tests.integration.test_config_integration", "TestFlextLdifSettingsIntegration"),
    "TestIncompleteEntries": ("tests.integration.test_error_recovery", "TestIncompleteEntries"),
    "TestInvalidSchemaDefinitions": ("tests.integration.test_error_recovery", "TestInvalidSchemaDefinitions"),
    "TestLargeAndComplexCases": ("tests.integration.test_edge_cases", "TestLargeAndComplexCases"),
    "TestMalformedLdifHandling": ("tests.integration.test_error_recovery", "TestMalformedLdifHandling"),
    "TestMinimalDifferencesOidOud": ("tests.integration.test_minimal_differences_metadata", "TestMinimalDifferencesOidOud"),
    "TestOidAclMetadataPreservation": ("tests.integration.test_acl_metadata_preservation", "TestOidAclMetadataPreservation"),
    "TestOidEntryIntegration": ("tests.integration.test_oid_integration", "TestOidEntryIntegration"),
    "TestOidQuirksTransformations": ("tests.integration.test_quirks_transformations", "TestOidQuirksTransformations"),
    "TestOidRoundTripIntegration": ("tests.integration.test_oid_integration", "TestOidRoundTripIntegration"),
    "TestOidSchemaIntegration": ("tests.integration.test_oid_integration", "TestOidSchemaIntegration"),
    "TestOidToOudAclConversion": ("tests.integration.test_cross_quirk_conversion", "TestOidToOudAclConversion"),
    "TestOidToOudIntegrationConversion": ("tests.integration.test_cross_quirk_conversion", "TestOidToOudIntegrationConversion"),
    "TestOidToOudSchemaConversion": ("tests.integration.test_cross_quirk_conversion", "TestOidToOudSchemaConversion"),
    "TestOudAciMetadataPreservation": ("tests.integration.test_acl_metadata_preservation", "TestOudAciMetadataPreservation"),
    "TestOudAclIntegration": ("tests.integration.test_oud_integration", "TestOudAclIntegration"),
    "TestOudEntryIntegration": ("tests.integration.test_oud_integration", "TestOudEntryIntegration"),
    "TestOudMetadataPreservation": ("tests.integration.test_oud_integration", "TestOudMetadataPreservation"),
    "TestOudQuirksTransformations": ("tests.integration.test_quirks_transformations", "TestOudQuirksTransformations"),
    "TestOudRoundTripIntegration": ("tests.integration.test_oud_integration", "TestOudRoundTripIntegration"),
    "TestOudSchemaIntegration": ("tests.integration.test_oud_integration", "TestOudSchemaIntegration"),
    "TestOudToOidAclMigration": ("tests.integration.test_oud_to_oid_migration", "TestOudToOidAclMigration"),
    "TestOudToOidEntryMigration": ("tests.integration.test_oud_to_oid_migration", "TestOudToOidEntryMigration"),
    "TestOudToOidFullMigration": ("tests.integration.test_oud_to_oid_migration", "TestOudToOidFullMigration"),
    "TestOudToOidSchemaMigration": ("tests.integration.test_oud_to_oid_migration", "TestOudToOidSchemaMigration"),
    "TestQuirksConversionMatrixFacade": ("tests.integration.test_cross_quirk_conversion", "TestQuirksConversionMatrixFacade"),
    "TestQuirksPropertyValidation": ("tests.integration.test_quirks_transformations", "TestQuirksPropertyValidation"),
    "TestRealLdapBatchOperations": ("tests.integration.test_real_ldap_crud", "TestRealLdapBatchOperations"),
    "TestRealLdapCRUD": ("tests.integration.test_real_ldap_crud", "TestRealLdapCRUD"),
    "TestRealLdapConfigurationFromEnv": ("tests.integration.test_real_ldap_config", "TestRealLdapConfigurationFromEnv"),
    "TestRealLdapExport": ("tests.integration.test_real_ldap_export", "TestRealLdapExport"),
    "TestRealLdapImport": ("tests.integration.test_real_ldap_import", "TestRealLdapImport"),
    "TestRealLdapRailwayComposition": ("tests.integration.test_real_ldap_config", "TestRealLdapRailwayComposition"),
    "TestRealLdapRoundtrip": ("tests.integration.test_real_ldap_roundtrip", "TestRealLdapRoundtrip"),
    "TestRfcDockerRealData": ("tests.integration.test_rfc_docker_real", "TestRfcDockerRealData"),
    "TestRfcExceptionHandlingRealScenarios": ("tests.integration.test_rfc_docker_real_integration", "TestRfcExceptionHandlingRealScenarios"),
    "TestRfcIntegrationRealWorld": ("tests.integration.test_rfc_docker_real", "TestRfcIntegrationRealWorld"),
    "TestRfcParserRealFixtures": ("tests.integration.test_rfc_docker_real_integration", "TestRfcParserRealFixtures"),
    "TestRfcSchemaParserRealFixtures": ("tests.integration.test_rfc_docker_real_integration", "TestRfcSchemaParserRealFixtures"),
    "TestRfcWriterRealFixtures": ("tests.integration.test_rfc_docker_real_integration", "TestRfcWriterRealFixtures"),
    "TestRoundtripEdgeCases": ("tests.integration.test_edge_cases", "TestRoundtripEdgeCases"),
    "TestSchemaDeviationsAttributeKeyCasing": ("tests.integration.test_zero_data_loss_schema", "TestSchemaDeviationsAttributeKeyCasing"),
    "TestSchemaDeviationsComplete": ("tests.integration.test_zero_data_loss_schema", "TestSchemaDeviationsComplete"),
    "TestSchemaDeviationsMissingSpaces": ("tests.integration.test_zero_data_loss_schema", "TestSchemaDeviationsMissingSpaces"),
    "TestSchemaDeviationsNameAliases": ("tests.integration.test_zero_data_loss_schema", "TestSchemaDeviationsNameAliases"),
    "TestSchemaDeviationsObsolete": ("tests.integration.test_zero_data_loss_schema", "TestSchemaDeviationsObsolete"),
    "TestSchemaDeviationsOriginalString": ("tests.integration.test_zero_data_loss_schema", "TestSchemaDeviationsOriginalString"),
    "TestSchemaDeviationsRoundTrip": ("tests.integration.test_zero_data_loss_schema", "TestSchemaDeviationsRoundTrip"),
    "TestSchemaDeviationsSpacing": ("tests.integration.test_zero_data_loss_schema", "TestSchemaDeviationsSpacing"),
    "TestSchemaDeviationsSyntaxQuotes": ("tests.integration.test_zero_data_loss_schema", "TestSchemaDeviationsSyntaxQuotes"),
    "TestSchemaDeviationsUtilities": ("tests.integration.test_zero_data_loss_schema", "TestSchemaDeviationsUtilities"),
    "TestSchemaDeviationsXOrigin": ("tests.integration.test_zero_data_loss_schema", "TestSchemaDeviationsXOrigin"),
    "TestSystematicFixtureCoverage": ("tests.integration.test_systematic_fixture_coverage", "TestSystematicFixtureCoverage"),
    "TestUnicodeBoundaries": ("tests.integration.test_edge_cases", "TestUnicodeBoundaries"),
    "TestZeroDataLossOidOud": ("tests.integration.test_zero_data_loss_oid_oud", "TestZeroDataLossOidOud"),
    "TestsFlextLdifFixtures": ("tests.integration.test_ldif_fixtures_integration", "TestsFlextLdifFixtures"),
    "WORKSPACE_ROOT": ("tests.integration.conftest", "WORKSPACE_ROOT"),
    "all_acl_fixtures": ("tests.integration.conftest", "all_acl_fixtures"),
    "all_entries_fixtures": ("tests.integration.conftest", "all_entries_fixtures"),
    "all_integration_fixtures": ("tests.integration.conftest", "all_integration_fixtures"),
    "all_schema_fixtures": ("tests.integration.conftest", "all_schema_fixtures"),
    "api": ("tests.integration.conftest", "api"),
    "clean_test_ou": ("tests.integration.conftest", "clean_test_ou"),
    "conversion_matrix": ("tests.integration.conftest", "conversion_matrix"),
    "fixtures_dir": ("tests.integration.test_quirks_transformations", "fixtures_dir"),
    "ldap_connection": ("tests.integration.conftest", "ldap_connection"),
    "ldap_container": ("tests.integration.conftest", "ldap_container"),
    "ldap_container_shared": ("tests.integration.conftest", "ldap_container_shared"),
    "logger": ("tests.integration.test_config_integration", "logger"),
    "make_test_base_dn": ("tests.integration.conftest", "make_test_base_dn"),
    "make_test_username": ("tests.integration.conftest", "make_test_username"),
    "migration_inputs": ("tests.integration.test_quirks_transformations", "migration_inputs"),
    "oid_acl_fixture": ("tests.integration.conftest", "oid_acl_fixture"),
    "oid_acl_quirk": ("tests.integration.conftest", "oid_acl_quirk"),
    "oid_entries": ("tests.integration.conftest", "oid_entries"),
    "oid_entries_fixture": ("tests.integration.conftest", "oid_entries_fixture"),
    "oid_integration_fixture": ("tests.integration.conftest", "oid_integration_fixture"),
    "oid_quirk": ("tests.integration.conftest", "oid_quirk"),
    "oid_schema_entries": ("tests.integration.conftest", "oid_schema_entries"),
    "oid_schema_fixture": ("tests.integration.conftest", "oid_schema_fixture"),
    "oid_schema_quirk": ("tests.integration.conftest", "oid_schema_quirk"),
    "openldap_acl_fixture": ("tests.integration.conftest", "openldap_acl_fixture"),
    "openldap_entries": ("tests.integration.conftest", "openldap_entries"),
    "openldap_entries_fixture": ("tests.integration.conftest", "openldap_entries_fixture"),
    "openldap_integration_fixture": ("tests.integration.conftest", "openldap_integration_fixture"),
    "openldap_schema_entries": ("tests.integration.conftest", "openldap_schema_entries"),
    "openldap_schema_fixture": ("tests.integration.conftest", "openldap_schema_fixture"),
    "oud_acl_fixture": ("tests.integration.conftest", "oud_acl_fixture"),
    "oud_acl_quirk": ("tests.integration.conftest", "oud_acl_quirk"),
    "oud_entries": ("tests.integration.conftest", "oud_entries"),
    "oud_entries_fixture": ("tests.integration.conftest", "oud_entries_fixture"),
    "oud_integration_fixture": ("tests.integration.conftest", "oud_integration_fixture"),
    "oud_quirk": ("tests.integration.conftest", "oud_quirk"),
    "oud_schema_entries": ("tests.integration.conftest", "oud_schema_entries"),
    "oud_schema_fixture": ("tests.integration.conftest", "oud_schema_fixture"),
    "oud_schema_quirk": ("tests.integration.conftest", "oud_schema_quirk"),
    "parser": ("tests.integration.conftest", "parser"),
    "rfc_schema_entries": ("tests.integration.conftest", "rfc_schema_entries"),
    "rfc_schema_fixture": ("tests.integration.conftest", "rfc_schema_fixture"),
    "server": ("tests.integration.conftest", "server"),
    "test_create_and_export_entry": ("tests.integration.test_simple_ldap", "test_create_and_export_entry"),
    "test_ldap_connection": ("tests.integration.test_simple_ldap", "test_ldap_connection"),
    "test_simple_ldap_search": ("tests.integration.test_simple_ldap", "test_simple_ldap_search"),
    "tmp_ldif_path": ("tests.integration.conftest", "tmp_ldif_path"),
    "u": ("tests.integration.test_zero_data_loss_schema", "TestSchemaDeviationsUtilities"),
    "unique_dn_suffix": ("tests.integration.conftest", "unique_dn_suffix"),
    "writer": ("tests.integration.conftest", "writer"),
}

__all__ = [
    "LDAP_ADMIN_DN",
    "LDAP_ADMIN_PASSWORD",
    "LDAP_BASE_DN",
    "LDAP_COMPOSE_FILE",
    "LDAP_CONTAINER_NAME",
    "LDAP_PORT",
    "LDAP_SERVICE_NAME",
    "WORKSPACE_ROOT",
    "APIScenarios",
    "ConfigTestData",
    "TestAclRoundTripPreservation",
    "TestBoundaryValues",
    "TestCategorizationRealData",
    "TestData",
    "TestDnCaseNormalizationScenarios",
    "TestDnCaseRegistry",
    "TestEmptyAndMinimalCases",
    "TestEncodingErrors",
    "TestFlextLdifAPIIntegration",
    "TestFlextLdifFacadeWorkflows",
    "TestFlextLdifSettingsIntegration",
    "TestIncompleteEntries",
    "TestInvalidSchemaDefinitions",
    "TestLargeAndComplexCases",
    "TestMalformedLdifHandling",
    "TestMinimalDifferencesOidOud",
    "TestOidAclMetadataPreservation",
    "TestOidEntryIntegration",
    "TestOidQuirksTransformations",
    "TestOidRoundTripIntegration",
    "TestOidSchemaIntegration",
    "TestOidToOudAclConversion",
    "TestOidToOudIntegrationConversion",
    "TestOidToOudSchemaConversion",
    "TestOudAciMetadataPreservation",
    "TestOudAclIntegration",
    "TestOudEntryIntegration",
    "TestOudMetadataPreservation",
    "TestOudQuirksTransformations",
    "TestOudRoundTripIntegration",
    "TestOudSchemaIntegration",
    "TestOudToOidAclMigration",
    "TestOudToOidEntryMigration",
    "TestOudToOidFullMigration",
    "TestOudToOidSchemaMigration",
    "TestQuirksConversionMatrixFacade",
    "TestQuirksPropertyValidation",
    "TestRealLdapBatchOperations",
    "TestRealLdapCRUD",
    "TestRealLdapConfigurationFromEnv",
    "TestRealLdapExport",
    "TestRealLdapImport",
    "TestRealLdapRailwayComposition",
    "TestRealLdapRoundtrip",
    "TestRfcDockerRealData",
    "TestRfcExceptionHandlingRealScenarios",
    "TestRfcIntegrationRealWorld",
    "TestRfcParserRealFixtures",
    "TestRfcSchemaParserRealFixtures",
    "TestRfcWriterRealFixtures",
    "TestRoundtripEdgeCases",
    "TestSchemaDeviationsAttributeKeyCasing",
    "TestSchemaDeviationsComplete",
    "TestSchemaDeviationsMissingSpaces",
    "TestSchemaDeviationsNameAliases",
    "TestSchemaDeviationsObsolete",
    "TestSchemaDeviationsOriginalString",
    "TestSchemaDeviationsRoundTrip",
    "TestSchemaDeviationsSpacing",
    "TestSchemaDeviationsSyntaxQuotes",
    "TestSchemaDeviationsUtilities",
    "TestSchemaDeviationsXOrigin",
    "TestSystematicFixtureCoverage",
    "TestUnicodeBoundaries",
    "TestZeroDataLossOidOud",
    "TestsFlextLdifFixtures",
    "all_acl_fixtures",
    "all_entries_fixtures",
    "all_integration_fixtures",
    "all_schema_fixtures",
    "api",
    "clean_test_ou",
    "conversion_matrix",
    "fixtures_dir",
    "ldap_connection",
    "ldap_container",
    "ldap_container_shared",
    "logger",
    "make_test_base_dn",
    "make_test_username",
    "migration_inputs",
    "oid_acl_fixture",
    "oid_acl_quirk",
    "oid_entries",
    "oid_entries_fixture",
    "oid_integration_fixture",
    "oid_quirk",
    "oid_schema_entries",
    "oid_schema_fixture",
    "oid_schema_quirk",
    "openldap_acl_fixture",
    "openldap_entries",
    "openldap_entries_fixture",
    "openldap_integration_fixture",
    "openldap_schema_entries",
    "openldap_schema_fixture",
    "oud_acl_fixture",
    "oud_acl_quirk",
    "oud_entries",
    "oud_entries_fixture",
    "oud_integration_fixture",
    "oud_quirk",
    "oud_schema_entries",
    "oud_schema_fixture",
    "oud_schema_quirk",
    "parser",
    "rfc_schema_entries",
    "rfc_schema_fixture",
    "server",
    "test_create_and_export_entry",
    "test_ldap_connection",
    "test_simple_ldap_search",
    "tmp_ldif_path",
    "u",
    "unique_dn_suffix",
    "writer",
]


def __getattr__(name: str) -> FlextTypes.ModuleExport:
    """Lazy-load module attributes on first access (PEP 562)."""
    return lazy_getattr(name, _LAZY_IMPORTS, globals(), __name__)


def __dir__() -> list[str]:
    """Return list of available attributes for dir() and autocomplete."""
    return sorted(__all__)


cleanup_submodule_namespace(__name__, _LAZY_IMPORTS)
