from pathlib import Path

import pytest

class TestCLIConsolidated:
    @pytest.fixture
    def sample_ldif_file(self) -> Path: ...
    def test_cli_main_available(self) -> None: ...
    def test_cli_help_command(self) -> None: ...
    def test_cli_parse_command(self, sample_ldif_file: Path) -> None: ...
    def test_cli_validate_command(self, sample_ldif_file: Path) -> None: ...
    def test_cli_with_invalid_file(self) -> None: ...
