# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make codegen
#
"""Flext ldif package."""

from __future__ import annotations

from typing import TYPE_CHECKING

from flext_core.lazy import cleanup_submodule_namespace, lazy_getattr

if TYPE_CHECKING:
    from flext_core import d, e, h, r, s, x
    from flext_core.typings import FlextTypes

    from flext_ldif import _models, _utilities, servers, services
    from flext_ldif.__version__ import (
        __all__,
        __author__,
        __author_email__,
        __description__,
        __license__,
        __title__,
        __url__,
        __version__,
        __version_info__,
    )
    from flext_ldif._models import (
        AclElement,
        FlextLdifModelsBase,
        FlextLdifModelsBases,
        FlextLdifModelsCollections,
        FlextLdifModelsConversions,
        FlextLdifModelsDomainAttributes,
        FlextLdifModelsDomainOperations,
        FlextLdifModelsDomains,
        FlextLdifModelsEvents,
        FlextLdifModelsMetadata,
        FlextLdifModelsProcessing,
        FlextLdifModelsResults,
        FlextLdifModelsSettings,
        FrozenIgnoreLdifModel,
        FrozenLdifModel,
        MutableIgnoreLdifModel,
        SchemaDiscovery,
        SchemaElement,
        SchemaLookup,
    )
    from flext_ldif._utilities import (
        AndFilter,
        ByAttrsFilter,
        ByAttrValueFilter,
        ByDnFilter,
        ByDnUnderBaseFilter,
        ByObjectClassFilter,
        ConvertBooleansTransformer,
        CustomFilter,
        CustomTransformer,
        DnOps,
        EntryOps,
        ExcludeAttrsFilter,
        Filter,
        FilterAttrsTransformer,
        FilterConfigBuilder,
        FlextFunctional,
        FlextLdifTypeHelpers,
        FlextLdifUtilitiesACL,
        FlextLdifUtilitiesAttribute,
        FlextLdifUtilitiesDecorators,
        FlextLdifUtilitiesDetection,
        FlextLdifUtilitiesDN,
        FlextLdifUtilitiesEntry,
        FlextLdifUtilitiesEvents,
        FlextLdifUtilitiesFilters,
        FlextLdifUtilitiesMetadata,
        FlextLdifUtilitiesObjectClass,
        FlextLdifUtilitiesOID,
        FlextLdifUtilitiesParser,
        FlextLdifUtilitiesParsers,
        FlextLdifUtilitiesResult,
        FlextLdifUtilitiesSchema,
        FlextLdifUtilitiesServer,
        FlextLdifUtilitiesTransformer,
        FlextLdifUtilitiesTypeGuards,
        FlextLdifUtilitiesValidation,
        FlextLdifUtilitiesWriter,
        FlextLdifUtilitiesWriters,
        IsSchemaFlextLdifUtilitiesFilters,
        Normalize,
        NormalizeAttrsTransformer,
        NormalizeDnTransformer,
        NotFilter,
        OrFilter,
        Pipeline,
        PipelineStep,
        ProcessConfigBuilder,
        RemoveAttrsTransformer,
        ReplaceBaseDnTransformer,
        Transform,
        TransformConfigBuilder,
        ValidationPipeline,
        ValidationResult,
        WriteConfigBuilder,
        f,
        logger,
    )
    from flext_ldif.api import FlextLdif
    from flext_ldif.base import FlextLdifServiceBase
    from flext_ldif.constants import FlextLdifConstants, FlextLdifConstants as c
    from flext_ldif.models import FlextLdifModels, FlextLdifModels as m
    from flext_ldif.protocols import FlextLdifProtocols, FlextLdifProtocols as p
    from flext_ldif.servers import (
        FlextLdifServersAd,
        FlextLdifServersApache,
        FlextLdifServersBase,
        FlextLdifServersBaseConstants,
        FlextLdifServersBaseEntry,
        FlextLdifServersBaseQuirkHelpers,
        FlextLdifServersBaseSchema,
        FlextLdifServersBaseSchemaAcl,
        FlextLdifServersDs389,
        FlextLdifServersNovell,
        FlextLdifServersOid,
        FlextLdifServersOidAcl,
        FlextLdifServersOidConstants,
        FlextLdifServersOidEntry,
        FlextLdifServersOidSchema,
        FlextLdifServersOpenldap,
        FlextLdifServersOpenldap1,
        FlextLdifServersOud,
        FlextLdifServersOudAcl,
        FlextLdifServersOudConstants,
        FlextLdifServersOudEntry,
        FlextLdifServersOudSchema,
        FlextLdifServersOudUtilities,
        FlextLdifServersRelaxed,
        FlextLdifServersRfc,
        FlextLdifServersRfcAcl,
        FlextLdifServersRfcConstants,
        FlextLdifServersRfcEntry,
        FlextLdifServersRfcSchema,
        FlextLdifServersTivoli,
        QuirkMethodsMixin,
    )
    from flext_ldif.services import (
        FlextLdifAcl,
        FlextLdifAnalysis,
        FlextLdifCategorization,
        FlextLdifConversion,
        FlextLdifDetector,
        FlextLdifDn,
        FlextLdifEntries,
        FlextLdifFilters,
        FlextLdifMigrationPipeline,
        FlextLdifParser,
        FlextLdifProcessing,
        FlextLdifProcessingPipelineService,
        FlextLdifSchema,
        FlextLdifServer,
        FlextLdifServiceRegistry,
        FlextLdifSorting,
        FlextLdifStatistics,
        FlextLdifSyntax,
        FlextLdifValidation,
        FlextLdifWriter,
        ProcessingPipeline,
        ServerTransformer,
    )
    from flext_ldif.settings import FlextLdifSettings
    from flext_ldif.shared import FlextLdifShared
    from flext_ldif.typings import FlextLdifTypes, FlextLdifTypes as t
    from flext_ldif.utilities import FlextLdifUtilities, FlextLdifUtilities as u

_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    "AclElement": ("flext_ldif._models", "AclElement"),
    "AndFilter": ("flext_ldif._utilities", "AndFilter"),
    "ByAttrValueFilter": ("flext_ldif._utilities", "ByAttrValueFilter"),
    "ByAttrsFilter": ("flext_ldif._utilities", "ByAttrsFilter"),
    "ByDnFilter": ("flext_ldif._utilities", "ByDnFilter"),
    "ByDnUnderBaseFilter": ("flext_ldif._utilities", "ByDnUnderBaseFilter"),
    "ByObjectClassFilter": ("flext_ldif._utilities", "ByObjectClassFilter"),
    "ConvertBooleansTransformer": (
        "flext_ldif._utilities",
        "ConvertBooleansTransformer",
    ),
    "CustomFilter": ("flext_ldif._utilities", "CustomFilter"),
    "CustomTransformer": ("flext_ldif._utilities", "CustomTransformer"),
    "DnOps": ("flext_ldif._utilities", "DnOps"),
    "EntryOps": ("flext_ldif._utilities", "EntryOps"),
    "ExcludeAttrsFilter": ("flext_ldif._utilities", "ExcludeAttrsFilter"),
    "Filter": ("flext_ldif._utilities", "Filter"),
    "FilterAttrsTransformer": ("flext_ldif._utilities", "FilterAttrsTransformer"),
    "FilterConfigBuilder": ("flext_ldif._utilities", "FilterConfigBuilder"),
    "FlextFunctional": ("flext_ldif._utilities", "FlextFunctional"),
    "FlextLdif": ("flext_ldif.api", "FlextLdif"),
    "FlextLdifAcl": ("flext_ldif.services", "FlextLdifAcl"),
    "FlextLdifAnalysis": ("flext_ldif.services", "FlextLdifAnalysis"),
    "FlextLdifCategorization": ("flext_ldif.services", "FlextLdifCategorization"),
    "FlextLdifConstants": ("flext_ldif.constants", "FlextLdifConstants"),
    "FlextLdifConversion": ("flext_ldif.services", "FlextLdifConversion"),
    "FlextLdifDetector": ("flext_ldif.services", "FlextLdifDetector"),
    "FlextLdifDn": ("flext_ldif.services", "FlextLdifDn"),
    "FlextLdifEntries": ("flext_ldif.services", "FlextLdifEntries"),
    "FlextLdifFilters": ("flext_ldif.services", "FlextLdifFilters"),
    "FlextLdifMigrationPipeline": ("flext_ldif.services", "FlextLdifMigrationPipeline"),
    "FlextLdifModels": ("flext_ldif.models", "FlextLdifModels"),
    "FlextLdifModelsBase": ("flext_ldif._models", "FlextLdifModelsBase"),
    "FlextLdifModelsBases": ("flext_ldif._models", "FlextLdifModelsBases"),
    "FlextLdifModelsCollections": ("flext_ldif._models", "FlextLdifModelsCollections"),
    "FlextLdifModelsConversions": ("flext_ldif._models", "FlextLdifModelsConversions"),
    "FlextLdifModelsDomainAttributes": (
        "flext_ldif._models",
        "FlextLdifModelsDomainAttributes",
    ),
    "FlextLdifModelsDomainOperations": (
        "flext_ldif._models",
        "FlextLdifModelsDomainOperations",
    ),
    "FlextLdifModelsDomains": ("flext_ldif._models", "FlextLdifModelsDomains"),
    "FlextLdifModelsEvents": ("flext_ldif._models", "FlextLdifModelsEvents"),
    "FlextLdifModelsMetadata": ("flext_ldif._models", "FlextLdifModelsMetadata"),
    "FlextLdifModelsProcessing": ("flext_ldif._models", "FlextLdifModelsProcessing"),
    "FlextLdifModelsResults": ("flext_ldif._models", "FlextLdifModelsResults"),
    "FlextLdifModelsSettings": ("flext_ldif._models", "FlextLdifModelsSettings"),
    "FlextLdifParser": ("flext_ldif.services", "FlextLdifParser"),
    "FlextLdifProcessing": ("flext_ldif.services", "FlextLdifProcessing"),
    "FlextLdifProcessingPipelineService": (
        "flext_ldif.services",
        "FlextLdifProcessingPipelineService",
    ),
    "FlextLdifProtocols": ("flext_ldif.protocols", "FlextLdifProtocols"),
    "FlextLdifSchema": ("flext_ldif.services", "FlextLdifSchema"),
    "FlextLdifServer": ("flext_ldif.services", "FlextLdifServer"),
    "FlextLdifServersAd": ("flext_ldif.servers", "FlextLdifServersAd"),
    "FlextLdifServersApache": ("flext_ldif.servers", "FlextLdifServersApache"),
    "FlextLdifServersBase": ("flext_ldif.servers", "FlextLdifServersBase"),
    "FlextLdifServersBaseConstants": (
        "flext_ldif.servers",
        "FlextLdifServersBaseConstants",
    ),
    "FlextLdifServersBaseEntry": ("flext_ldif.servers", "FlextLdifServersBaseEntry"),
    "FlextLdifServersBaseQuirkHelpers": (
        "flext_ldif.servers",
        "FlextLdifServersBaseQuirkHelpers",
    ),
    "FlextLdifServersBaseSchema": ("flext_ldif.servers", "FlextLdifServersBaseSchema"),
    "FlextLdifServersBaseSchemaAcl": (
        "flext_ldif.servers",
        "FlextLdifServersBaseSchemaAcl",
    ),
    "FlextLdifServersDs389": ("flext_ldif.servers", "FlextLdifServersDs389"),
    "FlextLdifServersNovell": ("flext_ldif.servers", "FlextLdifServersNovell"),
    "FlextLdifServersOid": ("flext_ldif.servers", "FlextLdifServersOid"),
    "FlextLdifServersOidAcl": ("flext_ldif.servers", "FlextLdifServersOidAcl"),
    "FlextLdifServersOidConstants": (
        "flext_ldif.servers",
        "FlextLdifServersOidConstants",
    ),
    "FlextLdifServersOidEntry": ("flext_ldif.servers", "FlextLdifServersOidEntry"),
    "FlextLdifServersOidSchema": ("flext_ldif.servers", "FlextLdifServersOidSchema"),
    "FlextLdifServersOpenldap": ("flext_ldif.servers", "FlextLdifServersOpenldap"),
    "FlextLdifServersOpenldap1": ("flext_ldif.servers", "FlextLdifServersOpenldap1"),
    "FlextLdifServersOud": ("flext_ldif.servers", "FlextLdifServersOud"),
    "FlextLdifServersOudAcl": ("flext_ldif.servers", "FlextLdifServersOudAcl"),
    "FlextLdifServersOudConstants": (
        "flext_ldif.servers",
        "FlextLdifServersOudConstants",
    ),
    "FlextLdifServersOudEntry": ("flext_ldif.servers", "FlextLdifServersOudEntry"),
    "FlextLdifServersOudSchema": ("flext_ldif.servers", "FlextLdifServersOudSchema"),
    "FlextLdifServersOudUtilities": (
        "flext_ldif.servers",
        "FlextLdifServersOudUtilities",
    ),
    "FlextLdifServersRelaxed": ("flext_ldif.servers", "FlextLdifServersRelaxed"),
    "FlextLdifServersRfc": ("flext_ldif.servers", "FlextLdifServersRfc"),
    "FlextLdifServersRfcAcl": ("flext_ldif.servers", "FlextLdifServersRfcAcl"),
    "FlextLdifServersRfcConstants": (
        "flext_ldif.servers",
        "FlextLdifServersRfcConstants",
    ),
    "FlextLdifServersRfcEntry": ("flext_ldif.servers", "FlextLdifServersRfcEntry"),
    "FlextLdifServersRfcSchema": ("flext_ldif.servers", "FlextLdifServersRfcSchema"),
    "FlextLdifServersTivoli": ("flext_ldif.servers", "FlextLdifServersTivoli"),
    "FlextLdifServiceBase": ("flext_ldif.base", "FlextLdifServiceBase"),
    "FlextLdifServiceRegistry": ("flext_ldif.services", "FlextLdifServiceRegistry"),
    "FlextLdifSettings": ("flext_ldif.settings", "FlextLdifSettings"),
    "FlextLdifShared": ("flext_ldif.shared", "FlextLdifShared"),
    "FlextLdifSorting": ("flext_ldif.services", "FlextLdifSorting"),
    "FlextLdifStatistics": ("flext_ldif.services", "FlextLdifStatistics"),
    "FlextLdifSyntax": ("flext_ldif.services", "FlextLdifSyntax"),
    "FlextLdifTypeHelpers": ("flext_ldif._utilities", "FlextLdifTypeHelpers"),
    "FlextLdifTypes": ("flext_ldif.typings", "FlextLdifTypes"),
    "FlextLdifUtilities": ("flext_ldif.utilities", "FlextLdifUtilities"),
    "FlextLdifUtilitiesACL": ("flext_ldif._utilities", "FlextLdifUtilitiesACL"),
    "FlextLdifUtilitiesAttribute": (
        "flext_ldif._utilities",
        "FlextLdifUtilitiesAttribute",
    ),
    "FlextLdifUtilitiesDN": ("flext_ldif._utilities", "FlextLdifUtilitiesDN"),
    "FlextLdifUtilitiesDecorators": (
        "flext_ldif._utilities",
        "FlextLdifUtilitiesDecorators",
    ),
    "FlextLdifUtilitiesDetection": (
        "flext_ldif._utilities",
        "FlextLdifUtilitiesDetection",
    ),
    "FlextLdifUtilitiesEntry": ("flext_ldif._utilities", "FlextLdifUtilitiesEntry"),
    "FlextLdifUtilitiesEvents": ("flext_ldif._utilities", "FlextLdifUtilitiesEvents"),
    "FlextLdifUtilitiesFilters": ("flext_ldif._utilities", "FlextLdifUtilitiesFilters"),
    "FlextLdifUtilitiesMetadata": (
        "flext_ldif._utilities",
        "FlextLdifUtilitiesMetadata",
    ),
    "FlextLdifUtilitiesOID": ("flext_ldif._utilities", "FlextLdifUtilitiesOID"),
    "FlextLdifUtilitiesObjectClass": (
        "flext_ldif._utilities",
        "FlextLdifUtilitiesObjectClass",
    ),
    "FlextLdifUtilitiesParser": ("flext_ldif._utilities", "FlextLdifUtilitiesParser"),
    "FlextLdifUtilitiesParsers": ("flext_ldif._utilities", "FlextLdifUtilitiesParsers"),
    "FlextLdifUtilitiesResult": ("flext_ldif._utilities", "FlextLdifUtilitiesResult"),
    "FlextLdifUtilitiesSchema": ("flext_ldif._utilities", "FlextLdifUtilitiesSchema"),
    "FlextLdifUtilitiesServer": ("flext_ldif._utilities", "FlextLdifUtilitiesServer"),
    "FlextLdifUtilitiesTransformer": (
        "flext_ldif._utilities",
        "FlextLdifUtilitiesTransformer",
    ),
    "FlextLdifUtilitiesTypeGuards": (
        "flext_ldif._utilities",
        "FlextLdifUtilitiesTypeGuards",
    ),
    "FlextLdifUtilitiesValidation": (
        "flext_ldif._utilities",
        "FlextLdifUtilitiesValidation",
    ),
    "FlextLdifUtilitiesWriter": ("flext_ldif._utilities", "FlextLdifUtilitiesWriter"),
    "FlextLdifUtilitiesWriters": ("flext_ldif._utilities", "FlextLdifUtilitiesWriters"),
    "FlextLdifValidation": ("flext_ldif.services", "FlextLdifValidation"),
    "FlextLdifWriter": ("flext_ldif.services", "FlextLdifWriter"),
    "FrozenIgnoreLdifModel": ("flext_ldif._models", "FrozenIgnoreLdifModel"),
    "FrozenLdifModel": ("flext_ldif._models", "FrozenLdifModel"),
    "IsSchemaFlextLdifUtilitiesFilters": (
        "flext_ldif._utilities",
        "IsSchemaFlextLdifUtilitiesFilters",
    ),
    "MutableIgnoreLdifModel": ("flext_ldif._models", "MutableIgnoreLdifModel"),
    "Normalize": ("flext_ldif._utilities", "Normalize"),
    "NormalizeAttrsTransformer": ("flext_ldif._utilities", "NormalizeAttrsTransformer"),
    "NormalizeDnTransformer": ("flext_ldif._utilities", "NormalizeDnTransformer"),
    "NotFilter": ("flext_ldif._utilities", "NotFilter"),
    "OrFilter": ("flext_ldif._utilities", "OrFilter"),
    "Pipeline": ("flext_ldif._utilities", "Pipeline"),
    "PipelineStep": ("flext_ldif._utilities", "PipelineStep"),
    "ProcessConfigBuilder": ("flext_ldif._utilities", "ProcessConfigBuilder"),
    "ProcessingPipeline": ("flext_ldif.services", "ProcessingPipeline"),
    "QuirkMethodsMixin": ("flext_ldif.servers", "QuirkMethodsMixin"),
    "RemoveAttrsTransformer": ("flext_ldif._utilities", "RemoveAttrsTransformer"),
    "ReplaceBaseDnTransformer": ("flext_ldif._utilities", "ReplaceBaseDnTransformer"),
    "SchemaDiscovery": ("flext_ldif._models", "SchemaDiscovery"),
    "SchemaElement": ("flext_ldif._models", "SchemaElement"),
    "SchemaLookup": ("flext_ldif._models", "SchemaLookup"),
    "ServerTransformer": ("flext_ldif.services", "ServerTransformer"),
    "Transform": ("flext_ldif._utilities", "Transform"),
    "TransformConfigBuilder": ("flext_ldif._utilities", "TransformConfigBuilder"),
    "ValidationPipeline": ("flext_ldif._utilities", "ValidationPipeline"),
    "ValidationResult": ("flext_ldif._utilities", "ValidationResult"),
    "WriteConfigBuilder": ("flext_ldif._utilities", "WriteConfigBuilder"),
    "__all__": ("flext_ldif.__version__", "__all__"),
    "__author__": ("flext_ldif.__version__", "__author__"),
    "__author_email__": ("flext_ldif.__version__", "__author_email__"),
    "__description__": ("flext_ldif.__version__", "__description__"),
    "__license__": ("flext_ldif.__version__", "__license__"),
    "__title__": ("flext_ldif.__version__", "__title__"),
    "__url__": ("flext_ldif.__version__", "__url__"),
    "__version__": ("flext_ldif.__version__", "__version__"),
    "__version_info__": ("flext_ldif.__version__", "__version_info__"),
    "_models": ("flext_ldif._models", ""),
    "_utilities": ("flext_ldif._utilities", ""),
    "c": ("flext_ldif.constants", "FlextLdifConstants"),
    "d": ("flext_core", "d"),
    "e": ("flext_core", "e"),
    "f": ("flext_ldif._utilities", "f"),
    "h": ("flext_core", "h"),
    "logger": ("flext_ldif._utilities", "logger"),
    "m": ("flext_ldif.models", "FlextLdifModels"),
    "p": ("flext_ldif.protocols", "FlextLdifProtocols"),
    "r": ("flext_core", "r"),
    "s": ("flext_core", "s"),
    "servers": ("flext_ldif.servers", ""),
    "services": ("flext_ldif.services", ""),
    "t": ("flext_ldif.typings", "FlextLdifTypes"),
    "u": ("flext_ldif.utilities", "FlextLdifUtilities"),
    "x": ("flext_core", "x"),
}

__all__ = [
    "AclElement",
    "AndFilter",
    "ByAttrValueFilter",
    "ByAttrsFilter",
    "ByDnFilter",
    "ByDnUnderBaseFilter",
    "ByObjectClassFilter",
    "ConvertBooleansTransformer",
    "CustomFilter",
    "CustomTransformer",
    "DnOps",
    "EntryOps",
    "ExcludeAttrsFilter",
    "Filter",
    "FilterAttrsTransformer",
    "FilterConfigBuilder",
    "FlextFunctional",
    "FlextLdif",
    "FlextLdifAcl",
    "FlextLdifAnalysis",
    "FlextLdifCategorization",
    "FlextLdifConstants",
    "FlextLdifConversion",
    "FlextLdifDetector",
    "FlextLdifDn",
    "FlextLdifEntries",
    "FlextLdifFilters",
    "FlextLdifMigrationPipeline",
    "FlextLdifModels",
    "FlextLdifModelsBase",
    "FlextLdifModelsBases",
    "FlextLdifModelsCollections",
    "FlextLdifModelsConversions",
    "FlextLdifModelsDomainAttributes",
    "FlextLdifModelsDomainOperations",
    "FlextLdifModelsDomains",
    "FlextLdifModelsEvents",
    "FlextLdifModelsMetadata",
    "FlextLdifModelsProcessing",
    "FlextLdifModelsResults",
    "FlextLdifModelsSettings",
    "FlextLdifParser",
    "FlextLdifProcessing",
    "FlextLdifProcessingPipelineService",
    "FlextLdifProtocols",
    "FlextLdifSchema",
    "FlextLdifServer",
    "FlextLdifServersAd",
    "FlextLdifServersApache",
    "FlextLdifServersBase",
    "FlextLdifServersBaseConstants",
    "FlextLdifServersBaseEntry",
    "FlextLdifServersBaseQuirkHelpers",
    "FlextLdifServersBaseSchema",
    "FlextLdifServersBaseSchemaAcl",
    "FlextLdifServersDs389",
    "FlextLdifServersNovell",
    "FlextLdifServersOid",
    "FlextLdifServersOidAcl",
    "FlextLdifServersOidConstants",
    "FlextLdifServersOidEntry",
    "FlextLdifServersOidSchema",
    "FlextLdifServersOpenldap",
    "FlextLdifServersOpenldap1",
    "FlextLdifServersOud",
    "FlextLdifServersOudAcl",
    "FlextLdifServersOudConstants",
    "FlextLdifServersOudEntry",
    "FlextLdifServersOudSchema",
    "FlextLdifServersOudUtilities",
    "FlextLdifServersRelaxed",
    "FlextLdifServersRfc",
    "FlextLdifServersRfcAcl",
    "FlextLdifServersRfcConstants",
    "FlextLdifServersRfcEntry",
    "FlextLdifServersRfcSchema",
    "FlextLdifServersTivoli",
    "FlextLdifServiceBase",
    "FlextLdifServiceRegistry",
    "FlextLdifSettings",
    "FlextLdifShared",
    "FlextLdifSorting",
    "FlextLdifStatistics",
    "FlextLdifSyntax",
    "FlextLdifTypeHelpers",
    "FlextLdifTypes",
    "FlextLdifUtilities",
    "FlextLdifUtilitiesACL",
    "FlextLdifUtilitiesAttribute",
    "FlextLdifUtilitiesDN",
    "FlextLdifUtilitiesDecorators",
    "FlextLdifUtilitiesDetection",
    "FlextLdifUtilitiesEntry",
    "FlextLdifUtilitiesEvents",
    "FlextLdifUtilitiesFilters",
    "FlextLdifUtilitiesMetadata",
    "FlextLdifUtilitiesOID",
    "FlextLdifUtilitiesObjectClass",
    "FlextLdifUtilitiesParser",
    "FlextLdifUtilitiesParsers",
    "FlextLdifUtilitiesResult",
    "FlextLdifUtilitiesSchema",
    "FlextLdifUtilitiesServer",
    "FlextLdifUtilitiesTransformer",
    "FlextLdifUtilitiesTypeGuards",
    "FlextLdifUtilitiesValidation",
    "FlextLdifUtilitiesWriter",
    "FlextLdifUtilitiesWriters",
    "FlextLdifValidation",
    "FlextLdifWriter",
    "FrozenIgnoreLdifModel",
    "FrozenLdifModel",
    "IsSchemaFlextLdifUtilitiesFilters",
    "MutableIgnoreLdifModel",
    "Normalize",
    "NormalizeAttrsTransformer",
    "NormalizeDnTransformer",
    "NotFilter",
    "OrFilter",
    "Pipeline",
    "PipelineStep",
    "ProcessConfigBuilder",
    "ProcessingPipeline",
    "QuirkMethodsMixin",
    "RemoveAttrsTransformer",
    "ReplaceBaseDnTransformer",
    "SchemaDiscovery",
    "SchemaElement",
    "SchemaLookup",
    "ServerTransformer",
    "Transform",
    "TransformConfigBuilder",
    "ValidationPipeline",
    "ValidationResult",
    "WriteConfigBuilder",
    "__all__",
    "__author__",
    "__author_email__",
    "__description__",
    "__license__",
    "__title__",
    "__url__",
    "__version__",
    "__version_info__",
    "_models",
    "_utilities",
    "c",
    "d",
    "e",
    "f",
    "h",
    "logger",
    "m",
    "p",
    "r",
    "s",
    "servers",
    "services",
    "t",
    "u",
    "x",
]


def __getattr__(name: str) -> FlextTypes.ModuleExport:
    """Lazy-load module attributes on first access (PEP 562)."""
    return lazy_getattr(name, _LAZY_IMPORTS, globals(), __name__)


def __dir__() -> list[str]:
    """Return list of available attributes for dir() and autocomplete."""
    return sorted(__all__)


cleanup_submodule_namespace(__name__, _LAZY_IMPORTS)
