# AUTO-GENERATED FILE — DO NOT EDIT MANUALLY.
# Regenerate with: make gen
#
"""Flext ldif package."""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import TYPE_CHECKING

from flext_core.lazy import install_lazy_exports

from flext_ldif.__version__ import (
    __author__,
    __author_email__,
    __description__,
    __license__,
    __title__,
    __url__,
    __version__,
    __version_info__,
)

if TYPE_CHECKING:
    from flext_core import *

    from flext_ldif import (
        api,
        base,
        constants,
        models,
        protocols,
        settings,
        shared,
        typings,
        utilities,
    )
    from flext_ldif._models import *
    from flext_ldif._utilities import *
    from flext_ldif.api import *
    from flext_ldif.base import *
    from flext_ldif.constants import *
    from flext_ldif.models import *
    from flext_ldif.protocols import *
    from flext_ldif.servers import *
    from flext_ldif.services import *
    from flext_ldif.settings import *
    from flext_ldif.shared import *
    from flext_ldif.typings import *
    from flext_ldif.utilities import *

_LAZY_IMPORTS: Mapping[str, str | Sequence[str]] = {
    "FlextLdif": "flext_ldif.api",
    "FlextLdifAcl": "flext_ldif.services.acl",
    "FlextLdifAnalysis": "flext_ldif.services.analysis",
    "FlextLdifCategorization": "flext_ldif.services.categorization",
    "FlextLdifConstants": "flext_ldif.constants",
    "FlextLdifConversion": "flext_ldif.services.conversion",
    "FlextLdifDetector": "flext_ldif.services.detector",
    "FlextLdifDetectorMixin": "flext_ldif.services.detector",
    "FlextLdifEntries": "flext_ldif.services.entries",
    "FlextLdifFilters": "flext_ldif.services.filters",
    "FlextLdifMigrationPipeline": "flext_ldif.services.migration",
    "FlextLdifModels": "flext_ldif.models",
    "FlextLdifModelsBases": "flext_ldif._models.base",
    "FlextLdifModelsCollections": "flext_ldif._models.collections",
    "FlextLdifModelsDomains": "flext_ldif._models.domain",
    "FlextLdifModelsDomainsEntries": "flext_ldif._models.domain_entries",
    "FlextLdifModelsEvents": "flext_ldif._models.events",
    "FlextLdifModelsMetadata": "flext_ldif._models.metadata",
    "FlextLdifModelsProcessing": "flext_ldif._models.processing",
    "FlextLdifModelsResults": "flext_ldif._models.results",
    "FlextLdifModelsSettings": "flext_ldif._models.settings",
    "FlextLdifParser": "flext_ldif.services.parser",
    "FlextLdifParserMixin": "flext_ldif.services.parser",
    "FlextLdifProcessing": "flext_ldif.services.processing",
    "FlextLdifProcessingPipeline": "flext_ldif.services.pipeline",
    "FlextLdifProcessingPipelineService": "flext_ldif.services._services.processing_pipeline_service",
    "FlextLdifProtocols": "flext_ldif.protocols",
    "FlextLdifQuirkMethodsMixin": "flext_ldif.servers._base.constants",
    "FlextLdifServer": "flext_ldif.services.server",
    "FlextLdifServersAd": "flext_ldif.servers.ad",
    "FlextLdifServersApache": "flext_ldif.servers.apache",
    "FlextLdifServersBase": "flext_ldif.servers.base",
    "FlextLdifServersBaseConstants": "flext_ldif.servers._base.constants",
    "FlextLdifServersBaseEntry": "flext_ldif.servers._base.entry",
    "FlextLdifServersBaseQuirkHelpers": "flext_ldif.servers._base.constants",
    "FlextLdifServersBaseSchema": "flext_ldif.servers._base.schema",
    "FlextLdifServersBaseSchemaAcl": "flext_ldif.servers._base.acl",
    "FlextLdifServersDs389": "flext_ldif.servers.ds389",
    "FlextLdifServersNovell": "flext_ldif.servers.novell",
    "FlextLdifServersOid": "flext_ldif.servers.oid",
    "FlextLdifServersOidAcl": "flext_ldif.servers._oid.acl",
    "FlextLdifServersOidConstants": "flext_ldif.servers._oid.constants",
    "FlextLdifServersOidEntry": "flext_ldif.servers._oid.entry",
    "FlextLdifServersOidSchema": "flext_ldif.servers._oid.schema",
    "FlextLdifServersOpenldap": "flext_ldif.servers.openldap",
    "FlextLdifServersOpenldap1": "flext_ldif.servers.openldap1",
    "FlextLdifServersOud": "flext_ldif.servers.oud",
    "FlextLdifServersOudAcl": "flext_ldif.servers._oud.acl",
    "FlextLdifServersOudConstants": "flext_ldif.servers._oud.constants",
    "FlextLdifServersOudEntry": "flext_ldif.servers._oud.entry",
    "FlextLdifServersOudSchema": "flext_ldif.servers._oud.schema",
    "FlextLdifServersOudUtilities": "flext_ldif.servers._oud.utilities",
    "FlextLdifServersRelaxed": "flext_ldif.servers.relaxed",
    "FlextLdifServersRfc": "flext_ldif.servers.rfc",
    "FlextLdifServersRfcAcl": "flext_ldif.servers._rfc.acl",
    "FlextLdifServersRfcConstants": "flext_ldif.servers._rfc.constants",
    "FlextLdifServersRfcEntry": "flext_ldif.servers._rfc.entry",
    "FlextLdifServersRfcSchema": "flext_ldif.servers._rfc.schema",
    "FlextLdifServersTivoli": "flext_ldif.servers.tivoli",
    "FlextLdifServiceBase": "flext_ldif.base",
    "FlextLdifSettings": "flext_ldif.settings",
    "FlextLdifShared": "flext_ldif.shared",
    "FlextLdifStatistics": "flext_ldif.services.statistics",
    "FlextLdifTransformer": "flext_ldif.services.transformers",
    "FlextLdifTypes": "flext_ldif.typings",
    "FlextLdifUtilities": "flext_ldif.utilities",
    "FlextLdifUtilitiesACL": "flext_ldif._utilities.acl",
    "FlextLdifUtilitiesAttribute": "flext_ldif._utilities.attribute",
    "FlextLdifUtilitiesCollectionLdif": "flext_ldif._utilities.collection_ldif",
    "FlextLdifUtilitiesDN": "flext_ldif._utilities.dn",
    "FlextLdifUtilitiesDetection": "flext_ldif._utilities.detection",
    "FlextLdifUtilitiesDispatch": "flext_ldif._utilities.dispatch",
    "FlextLdifUtilitiesEntry": "flext_ldif._utilities.entry",
    "FlextLdifUtilitiesEvents": "flext_ldif._utilities.events",
    "FlextLdifUtilitiesMetadata": "flext_ldif._utilities.metadata",
    "FlextLdifUtilitiesOID": "flext_ldif._utilities.oid",
    "FlextLdifUtilitiesObjectClass": "flext_ldif._utilities.object_class",
    "FlextLdifUtilitiesParser": "flext_ldif._utilities.parser",
    "FlextLdifUtilitiesParsers": "flext_ldif._utilities.parsers",
    "FlextLdifUtilitiesPipeline": "flext_ldif._utilities.pipeline",
    "FlextLdifUtilitiesResult": "flext_ldif._utilities.result",
    "FlextLdifUtilitiesSchema": "flext_ldif._utilities.schema",
    "FlextLdifUtilitiesServer": "flext_ldif._utilities.server",
    "FlextLdifUtilitiesTransformer": "flext_ldif._utilities.transformers",
    "FlextLdifUtilitiesTransformers": "flext_ldif._utilities.transformers",
    "FlextLdifUtilitiesValidation": "flext_ldif._utilities.validation",
    "FlextLdifUtilitiesWriter": "flext_ldif._utilities.writer",
    "FlextLdifUtilitiesWriters": "flext_ldif._utilities.writers",
    "FlextLdifValidation": "flext_ldif.services.rfc_validation",
    "FlextLdifWriter": "flext_ldif.services.writer",
    "FlextLdifWriterMixin": "flext_ldif.services.writer",
    "_models": "flext_ldif._models",
    "_utilities": "flext_ldif._utilities",
    "acl": "flext_ldif._utilities.acl",
    "ad": "flext_ldif.servers.ad",
    "analysis": "flext_ldif.services.analysis",
    "apache": "flext_ldif.servers.apache",
    "api": "flext_ldif.api",
    "attribute": "flext_ldif._utilities.attribute",
    "base": "flext_ldif.base",
    "c": ["flext_ldif.constants", "FlextLdifConstants"],
    "categorization": "flext_ldif.services.categorization",
    "collection_ldif": "flext_ldif._utilities.collection_ldif",
    "collections": "flext_ldif._models.collections",
    "constants": "flext_ldif.constants",
    "conversion": "flext_ldif.services.conversion",
    "d": "flext_core",
    "detection": "flext_ldif._utilities.detection",
    "detector": "flext_ldif.services.detector",
    "dispatch": "flext_ldif._utilities.dispatch",
    "dn": "flext_ldif._utilities.dn",
    "domain": "flext_ldif._models.domain",
    "domain_entries": "flext_ldif._models.domain_entries",
    "ds389": "flext_ldif.servers.ds389",
    "e": "flext_core",
    "entries": "flext_ldif.services.entries",
    "entry": "flext_ldif._utilities.entry",
    "events": "flext_ldif._models.events",
    "filters": "flext_ldif.services.filters",
    "h": "flext_core",
    "ldif": "flext_ldif.api",
    "logger": "flext_ldif.servers.oid",
    "m": ["flext_ldif.models", "FlextLdifModels"],
    "metadata": "flext_ldif._models.metadata",
    "migration": "flext_ldif.services.migration",
    "models": "flext_ldif.models",
    "novell": "flext_ldif.servers.novell",
    "object_class": "flext_ldif._utilities.object_class",
    "oid": "flext_ldif._utilities.oid",
    "openldap": "flext_ldif.servers.openldap",
    "openldap1": "flext_ldif.servers.openldap1",
    "oud": "flext_ldif.servers.oud",
    "p": ["flext_ldif.protocols", "FlextLdifProtocols"],
    "parser": "flext_ldif._utilities.parser",
    "parsers": "flext_ldif._utilities.parsers",
    "pipeline": "flext_ldif._utilities.pipeline",
    "processing": "flext_ldif._models.processing",
    "processing_pipeline_service": "flext_ldif.services._services.processing_pipeline_service",
    "protocols": "flext_ldif.protocols",
    "r": "flext_core",
    "relaxed": "flext_ldif.servers.relaxed",
    "result": "flext_ldif._utilities.result",
    "results": "flext_ldif._models.results",
    "rfc": "flext_ldif.servers.rfc",
    "rfc_validation": "flext_ldif.services.rfc_validation",
    "s": "flext_ldif.base",
    "schema": "flext_ldif._utilities.schema",
    "server": "flext_ldif._utilities.server",
    "servers": "flext_ldif.servers",
    "services": "flext_ldif.services",
    "settings": "flext_ldif.settings",
    "shared": "flext_ldif.shared",
    "statistics": "flext_ldif.services.statistics",
    "t": ["flext_ldif.typings", "FlextLdifTypes"],
    "tivoli": "flext_ldif.servers.tivoli",
    "transformers": "flext_ldif._utilities.transformers",
    "typings": "flext_ldif.typings",
    "u": ["flext_ldif.utilities", "FlextLdifUtilities"],
    "utilities": "flext_ldif.utilities",
    "validation": "flext_ldif._utilities.validation",
    "writer": "flext_ldif._utilities.writer",
    "writers": "flext_ldif._utilities.writers",
    "x": "flext_core",
}


install_lazy_exports(__name__, globals(), _LAZY_IMPORTS, sorted(_LAZY_IMPORTS))
