"""Root public lazy export contract for flext_ldif."""

from __future__ import annotations

from flext_core.lazy import build_lazy_import_map

FLEXT_LDIF_LAZY_IMPORTS = build_lazy_import_map(
    {
        ".api": ("FlextLdif", "ldif"),
        ".base": ("FlextLdifServiceBase", "s"),
        ".constants": ("FlextLdifConstants", "c"),
        ".models": ("FlextLdifModels", "m"),
        ".protocols": ("FlextLdifProtocols", "p"),
        ".servers.ad": ("FlextLdifServersAd",),
        ".servers.apache": ("FlextLdifServersApache",),
        ".servers.base": ("FlextLdifServersBase",),
        ".servers.ds389": ("FlextLdifServersDs389",),
        ".servers.novell": ("FlextLdifServersNovell",),
        ".servers.oid": ("FlextLdifServersOid",),
        ".servers.openldap": ("FlextLdifServersOpenldap",),
        ".servers.openldap1": ("FlextLdifServersOpenldap1",),
        ".servers.oud": ("FlextLdifServersOud",),
        ".servers.relaxed": ("FlextLdifServersRelaxed",),
        ".servers.rfc": ("FlextLdifServersRfc",),
        ".servers.tivoli": ("FlextLdifServersTivoli",),
        ".services.acl": ("FlextLdifAcl",),
        ".services.analysis": ("FlextLdifAnalysis",),
        ".services.categorization": ("FlextLdifCategorization",),
        ".services.conversion": ("FlextLdifConversion",),
        ".services.conversion_acl": ("FlextLdifConversionAclMixin",),
        ".services.conversion_acl_preserve": ("FlextLdifConversionAclPreserveMixin",),
        ".services.conversion_entry": ("FlextLdifConversionEntryMixin",),
        ".services.conversion_metadata": ("FlextLdifConversionMetadataMixin",),
        ".services.conversion_schema": ("FlextLdifConversionSchemaMixin",),
        ".services.conversion_schema_entry": ("FlextLdifConversionSchemaEntryMixin",),
        ".services.conversion_support": ("FlextLdifConversionSupportMixin",),
        ".services.detector": ("FlextLdifDetector",),
        ".services.entries": ("FlextLdifEntries",),
        ".services.filters": ("FlextLdifFilters",),
        ".services.migration": ("FlextLdifMigrationPipeline",),
        ".services.parser": ("FlextLdifParser",),
        ".services.pipeline": ("FlextLdifProcessingPipeline",),
        ".services.processing": ("FlextLdifProcessing",),
        ".services.server": ("FlextLdifServer",),
        ".services.statistics": ("FlextLdifStatistics",),
        ".services.transformers": ("FlextLdifTransformer",),
        ".services.validation": ("FlextLdifValidation",),
        ".services.writer": ("FlextLdifWriter",),
        ".settings": ("FlextLdifSettings",),
        ".shared": ("FlextLdifShared",),
        ".typings": ("FlextLdifTypes", "t"),
        ".utilities": ("FlextLdifUtilities", "u"),
    },
)

FLEXT_LDIF_PUBLIC_EXPORTS: tuple[str, ...] = (
    "FlextLdif",
    "FlextLdifAcl",
    "FlextLdifAnalysis",
    "FlextLdifCategorization",
    "FlextLdifConstants",
    "FlextLdifConversion",
    "FlextLdifConversionAclMixin",
    "FlextLdifConversionAclPreserveMixin",
    "FlextLdifConversionEntryMixin",
    "FlextLdifConversionMetadataMixin",
    "FlextLdifConversionSchemaEntryMixin",
    "FlextLdifConversionSchemaMixin",
    "FlextLdifConversionSupportMixin",
    "FlextLdifDetector",
    "FlextLdifEntries",
    "FlextLdifFilters",
    "FlextLdifMigrationPipeline",
    "FlextLdifModels",
    "FlextLdifParser",
    "FlextLdifProcessing",
    "FlextLdifProcessingPipeline",
    "FlextLdifProtocols",
    "FlextLdifServer",
    "FlextLdifServersAd",
    "FlextLdifServersApache",
    "FlextLdifServersBase",
    "FlextLdifServersDs389",
    "FlextLdifServersNovell",
    "FlextLdifServersOid",
    "FlextLdifServersOpenldap",
    "FlextLdifServersOpenldap1",
    "FlextLdifServersOud",
    "FlextLdifServersRelaxed",
    "FlextLdifServersRfc",
    "FlextLdifServersTivoli",
    "FlextLdifServiceBase",
    "FlextLdifSettings",
    "FlextLdifShared",
    "FlextLdifStatistics",
    "FlextLdifTransformer",
    "FlextLdifTypes",
    "FlextLdifUtilities",
    "FlextLdifValidation",
    "FlextLdifWriter",
    "__author__",
    "__author_email__",
    "__description__",
    "__license__",
    "__title__",
    "__url__",
    "__version__",
    "__version_info__",
    "c",
    "d",
    "e",
    "h",
    "ldif",
    "m",
    "p",
    "r",
    "s",
    "t",
    "u",
    "x",
)

__all__: tuple[str, ...] = (
    "FLEXT_LDIF_LAZY_IMPORTS",
    "FLEXT_LDIF_PUBLIC_EXPORTS",
)
