# AUTO-GENERATED FILE — Regenerate with: make gen
"""Servers package."""

from __future__ import annotations

from flext_core.lazy import (
    build_lazy_import_map,
    install_lazy_exports,
    merge_lazy_imports,
)

_LAZY_IMPORTS = merge_lazy_imports(
    (
        "._base",
        "._oid",
        "._oud",
        "._rfc",
    ),
    build_lazy_import_map(
        {
            "._base": ("_base",),
            "._base.acl": ("FlextLdifServersBaseSchemaAcl",),
            "._base.constants": ("FlextLdifServersBaseConstants",),
            "._base.entry": ("FlextLdifServersBaseEntry",),
            "._base.mixins": ("FlextLdifServerMethodsMixin",),
            "._base.schema": ("FlextLdifServersBaseSchema",),
            "._oid": ("_oid",),
            "._oid.acl": ("FlextLdifServersOidAcl",),
            "._oid.acl_assemble": ("FlextLdifServersOidAclAssemble",),
            "._oid.acl_convert": ("FlextLdifServersOidAclConvert",),
            "._oid.acl_convert_oud": ("FlextLdifServersOidAclToOud",),
            "._oid.acl_pipeline": ("FlextLdifServersOidAclPipeline",),
            "._oid.acl_render": ("FlextLdifServersOidAclRender",),
            "._oid.constants": ("FlextLdifServersOidConstants",),
            "._oid.entry": ("FlextLdifServersOidEntry",),
            "._oid.schema": ("FlextLdifServersOidSchema",),
            "._oud": ("_oud",),
            "._oud.aci": ("FlextLdifServersOudAciMixin",),
            "._oud.acl": ("FlextLdifServersOudAcl",),
            "._oud.acl_extract": ("FlextLdifServersOudAclExtractMixin",),
            "._oud.acl_metadata": ("FlextLdifServersOudAclMetadataMixin",),
            "._oud.comments": ("FlextLdifServersOudCommentsMixin",),
            "._oud.constants": ("FlextLdifServersOudConstants",),
            "._oud.entry": ("FlextLdifServersOudEntry",),
            "._oud.helpers": ("FlextLdifServersOudHelpersMixin",),
            "._oud.schema": ("FlextLdifServersOudSchema",),
            "._oud.transform": ("FlextLdifServersOudTransformMixin",),
            "._oud.utilities": ("FlextLdifServersOudUtilities",),
            "._rfc": ("_rfc",),
            "._rfc.acl": ("FlextLdifServersRfcAcl",),
            "._rfc.constants": ("FlextLdifServersRfcConstants",),
            "._rfc.entry": ("FlextLdifServersRfcEntry",),
            "._rfc.schema": ("FlextLdifServersRfcSchema",),
            ".ad": ("FlextLdifServersAd",),
            ".apache": ("FlextLdifServersApache",),
            ".base": ("FlextLdifServersBase",),
            ".ds389": ("FlextLdifServersDs389",),
            ".novell": ("FlextLdifServersNovell",),
            ".oid": ("FlextLdifServersOid",),
            ".openldap": ("FlextLdifServersOpenldap",),
            ".openldap1": ("FlextLdifServersOpenldap1",),
            ".oud": ("FlextLdifServersOud",),
            ".relaxed": ("FlextLdifServersRelaxed",),
            ".rfc": ("FlextLdifServersRfc",),
            ".tivoli": ("FlextLdifServersTivoli",),
        },
    ),
    exclude_names=(
        "cleanup_submodule_namespace",
        "install_lazy_exports",
        "lazy_getattr",
        "logger",
        "merge_lazy_imports",
        "output",
        "output_reporting",
        "pytest_addoption",
        "pytest_collect_file",
        "pytest_collection_modifyitems",
        "pytest_configure",
        "pytest_runtest_setup",
        "pytest_runtest_teardown",
        "pytest_sessionfinish",
        "pytest_sessionstart",
        "pytest_terminal_summary",
        "pytest_warning_recorded",
    ),
    module_name=__name__,
)


install_lazy_exports(
    __name__,
    globals(),
    _LAZY_IMPORTS,
    publish_all=False,
)
