"""Exemplo de refatoração usando helpers para reduzir duplicação.

Este arquivo mostra como refatorar testes duplicados usando os helpers.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""

from __future__ import annotations

from tests import t

"\ndef test_schema_parse_attribute(self, rfc_schema_quirk) -> None:\n    attr_def = c.Ldif.Rfc.ATTR_DEF_CN_COMPLETE\n    result = rfc_schema_quirk._parse_attribute(attr_def)\n    assert result.is_success\n    attr = result.value\n    assert attr.oid == c.Ldif.Rfc.ATTR_OID_CN\n    assert attr.name == c.Ldif.Rfc.ATTR_NAME_CN\n\ndef test_schema_parse_another_attribute(self, rfc_schema_quirk) -> None:\n    attr_def = c.Ldif.Rfc.ATTR_DEF_SN\n    result = rfc_schema_quirk._parse_attribute(attr_def)\n    assert result.is_success\n    attr = result.value\n    assert attr.oid == c.Ldif.Rfc.ATTR_OID_SN\n    assert attr.name == c.Ldif.Rfc.ATTR_NAME_SN\n\ndef test_schema_parse_objectclass(self, rfc_schema_quirk) -> None:\n    oc_def = c.Ldif.Rfc.OC_DEF_PERSON_FULL\n    result = rfc_schema_quirk._parse_objectclass(oc_def)\n    assert result.is_success\n    oc = result.value\n    assert oc.oid == c.Ldif.Rfc.OC_OID_PERSON\n    assert oc.name == c.Ldif.Rfc.OC_NAME_PERSON\n"
"\nfrom .test_operations import TestOperations\n\ndef test_schema_parse_attribute(self, rfc_schema_quirk) -> None:\n    TestOperations.parse_attribute_and_validate(\n        rfc_schema_quirk,\n        c.Ldif.Rfc.ATTR_DEF_CN_COMPLETE,\n        expected_oid=c.Ldif.Rfc.ATTR_OID_CN,\n        expected_name=c.Ldif.Rfc.ATTR_NAME_CN,\n    )\n\ndef test_schema_parse_another_attribute(self, rfc_schema_quirk) -> None:\n    TestOperations.parse_attribute_and_validate(\n        rfc_schema_quirk,\n        c.Ldif.Rfc.ATTR_DEF_SN,\n        expected_oid=c.Ldif.Rfc.ATTR_OID_SN,\n        expected_name=c.Ldif.Rfc.ATTR_NAME_SN,\n    )\n\ndef test_schema_parse_objectclass(self, rfc_schema_quirk) -> None:\n    TestOperations.parse_objectclass_and_validate(\n        rfc_schema_quirk,\n        c.Ldif.Rfc.OC_DEF_PERSON_FULL,\n        expected_oid=c.Ldif.Rfc.OC_OID_PERSON,\n        expected_name=c.Ldif.Rfc.OC_NAME_PERSON,\n    )\n"
'\nimport pytest\nfrom .test_operations import TestOperations\n\n@pytest.mark.parametrize("attr_def,expected_oid,expected_name", [\n    (c.Ldif.Rfc.ATTR_DEF_CN_COMPLETE, c.Ldif.Rfc.ATTR_OID_CN, c.Ldif.Rfc.ATTR_NAME_CN),\n    (c.Ldif.Rfc.ATTR_DEF_SN, c.Ldif.Rfc.ATTR_OID_SN, c.Ldif.Rfc.ATTR_NAME_SN),\n    (c.Ldif.Rfc.ATTR_DEF_ST, c.Ldif.Rfc.ATTR_OID_ST, c.Ldif.Rfc.ATTR_NAME_ST),\n])\ndef test_schema_parse_multiple_attributes(\n    rfc_schema_quirk,\n    attr_def: str,\n    expected_oid: str,\n    expected_name: str,\n) -> None:\n    TestOperations.parse_attribute_and_validate(\n        rfc_schema_quirk, attr_def, expected_oid, expected_name\n    )\n'
'\ndef test_roundtrip_rfc_entries(self, ldif_api: ldif, tmp_path: Path) -> None:\n    entries = FlextLdifTestUtils.load_fixture(ldif_api, "rfc", "rfc_entries_fixtures.ldif")\n\n    write_result = ldif_api.write(entries)\n    assert write_result.is_success\n    ldif = write_result.value\n\n    output_file = tmp_path / "roundtrip.ldif"\n    output_file.write_text(ldif)\n\n    re_read_result = ldif_api.parse(output_file)\n    assert re_read_result.is_success\n    roundtripped_entries = re_read_result.value\n\n    assert len(roundtripped_entries) == len(entries)\n    for i, (orig, roundtrip) in enumerate(zip(entries, roundtripped_entries)):\n        assert orig.dn.value == roundtrip.dn.value\n'
'\nfrom .test_operations import TestOperations\n\ndef test_roundtrip_rfc_entries(self, ldif_api: ldif, tmp_path: Path) -> None:\n    fixture_path = FlextLdifTestUtils.get_fixture_path("rfc", "rfc_entries_fixtures.ldif")\n    original, roundtripped = TestOperations.roundtrip_and_validate(\n        ldif_api, fixture_path, tmp_path\n    )\n    # Helpers já validam count, DN preservation, etc.\n'
'\ndef test_write_entry(self, entry_quirk: FlextLdifServersOud.Entry) -> None:\n    entry = m.Ldif.Entry.create(\n        dn="cn=test,dc=example,dc=com",\n        attributes={"cn": ["test"], "objectClass": ["person"]},\n    ).value\n    result = entry_quirk.write(entry)\n    assert result.is_success\n    ldif = result.value\n    assert "dn: cn=test,dc=example,dc=com" in ldif\n'
'\nfrom .test_operations import TestOperations\n\ndef test_write_entry(self, entry_quirk: FlextLdifServersOud.Entry) -> None:\n    entry = m.Ldif.Entry.create(\n        dn="cn=test,dc=example,dc=com",\n        attributes={"cn": ["test"], "objectClass": ["person"]},\n    ).value\n    TestOperations.write_entry_and_validate(\n        entry_quirk, entry, expected_content="dn: cn=test,dc=example,dc=com"\n    )\n'
__all__: t.StrSequence = []
